matrix:
  include:
    - os: linux
      language: c
      dist: xenial
      sudo: required
      services: docker
      env:
        - arch_build=amd64
    - os: linux
      language: c
      dist: xenial
      sudo: required
      services: docker
      env: 
        - emu=true
        - arch_build=i386
      before_install:
        - . ./.travis/emu/install_prerequisities.sh
      script:
        - sudo sg sbuild -c "bash .travis/emu/i386_chroot.sh"
    - os: osx
      osx_image: xcode8.3
      language: objective-c
    - os: linux
      language: c
      dist: xenial
      sudo: required
      env: 
        - emu=true
        - arch_build=armhf
        - typec=1
      before_install:
        - . ./.travis/emu/install_prerequisities.sh
      before_script:
        - echo "skipped" # skip tag
      script:
        - sudo ./.travis/emu/armhf_chroot.sh
      deploy:
        skip_cleanup: true
        provider: script
        script: echo "skipped" # skip for now then move it from chroot
    - os: linux
      language: c
      dist: xenial
      sudo: required
      env: 
        - emu=true
        - arch_build=armhf
        - typec=2
      before_install:
        - . ./.travis/emu/install_prerequisities.sh
      before_script:
        - echo "skipped" # skip tag
      script:
        - sudo ./.travis/emu/armhf_chroot.sh
      deploy:
        skip_cleanup: true
        provider: script
        script: echo "skipped" # skip for now then move it from chroot
    - os: linux
      language: c
      dist: xenial
      sudo: required
      env: 
        - emu=true
        - arch_build=armhf
        - typec=3
      before_install:
        - . ./.travis/emu/install_prerequisities.sh
      before_script:
        - echo "skipped" # skip tag
      script:
        - sudo ./.travis/emu/armhf_chroot.sh
      deploy:
        skip_cleanup: true
        provider: script
        script: echo "skipped" # skip for now then move it from chroot
 # enable when aarch64 will support jit
    # - os: linux
    #   language: c
    #   dist: xenial
    #   sudo: required
    #   env: 
    #     - emu=true
    #     - arch_build=aarch
    #     - typec=1
    #   before_install:
    #     - . ./.travis/emu/install_prerequisities.sh
    #   before_script:
    #     - echo "skipped" # skip tag
    #   script:
    #     - sudo ./.travis/emu/aarch_chroot.sh
    #   deploy:
    #     skip_cleanup: true
    #     provider: script
    #     script: echo "skipped" # skip for now then move it from chroot
    - os: linux
      language: c
      dist: xenial
      sudo: required
      env: 
        - emu=true
        - arch_build=aarch
        - typec=2
      before_install:
        - . ./.travis/emu/install_prerequisities.sh
      before_script:
        - echo "skipped" # skip tag
      script:
        - sudo sg sbuild -c "bash .travis/emu/aarch_chroot.sh"
      deploy:
        skip_cleanup: true
        provider: script
        script: echo "skipped" # skip for now then move it from chroot
    - os: linux
      language: c
      dist: xenial
      sudo: required
      env: 
        - emu=true
        - arch_build=aarch
        - typec=3
      before_install:
        - . ./.travis/emu/install_prerequisities.sh
      before_script:
        - echo "skipped" # skip tag
      script:
        - sudo sg sbuild -c "bash .travis/emu/aarch_chroot.sh"
      deploy:
        skip_cleanup: true
        provider: script
        script: echo "skipped" # skip for now then move it from chroot
    - stage: deploy
      os: linux
      dist: xenial
      env: 
        - is=deploy
        - arch=armhf
      before_install:
        - .travis/install_ssh_id.sh
        - unset SSH_ID
        - . ./.travis/emu/install_prerequisities.sh
      script:
        - echo "skipped" # skip script tag
      services: docker
    - stage: deploy
      os: linux
      dist: xenial
      env: 
        - is=deploy
        - arch=aarch
      before_install:
        - .travis/install_ssh_id.sh
        - unset SSH_ID
        - . ./.travis/emu/install_prerequisities.sh
      script:
        - echo "skipped" # skip script tag
      services: docker
  allow_failures:
    - os: osx
      osx_image: xcode11.1
      language: objective-c

before_install:
  - .travis/install_ssh_id.sh
  - unset SSH_ID
  - .travis/install_prerequisities.sh

before_script:
  - . ./.travis/setup_env.sh

script:
  - . ./.travis/build.sh
        
branches:
  only:
    - master

compiler:
  - gcc

env:
  global:
    - MAKEFLAGS="-j 2"

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
