matrix:
  include:
    - os: linux
      language: c
      dist: xenial
      sudo: required
      services: docker
      before_install:
        - .travis/install_ssh_id.sh
        - unset SSH_ID
        - .travis/install_prerequisities.sh

      before_script:
        - . ./.travis/setup_env.sh

      script:
        - . ./.travis/build.sh
    - os: osx
      osx_image: xcode8.3
      language: objective-c
      before_install:
        - .travis/install_ssh_id.sh
        - unset SSH_ID
        - .travis/install_prerequisities.sh

      before_script:
        - . ./.travis/setup_env.sh

      script:
        - . ./.travis/build.sh
    - os: linux
      language: c
      dist: xenial
      sudo: required
      env: 
        - ar=arm
        - typec=1
      script:
        - . ./.travis/build.sh
    - os: linux
      language: c
      dist: xenial
      sudo: required
      env: 
        - ar=arm
        - typec=2
      script:
        - . ./.travis/build.sh
    - os: linux
      language: c
      dist: xenial
      sudo: required
      env: 
        - ar=arm
        - typec=3
      script:
        - . ./.travis/build.sh
    - stage: deploy
      os: linux
      dist: xenial
      env: 
        - is=deploy
      before_install:
        - .travis/install_ssh_id.sh
        - unset SSH_ID
        - .travis/install_prerequisities.sh

      before_script:
        - . ./.travis/setup_env.sh

      script:
        - . ./.travis/build.sh
      services: docker
        
branches:
  only:
    - master

compiler:
  - gcc

env:
  global:
    - MAKEFLAGS="-j 2"

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
