	{"OSMesaCreateLDG",
	"void *OSMesaCreateLDG( long format, long type, long WIDTH, long HEIGHT )",
	OSMesaCreateLDG},
	{"OSMesaDestroyLDG",
	"void OSMesaDestroyLDG(void)",
	OSMesaDestroyLDG},
	{"max_width",
	"long max_width(void)",
	max_width},
	{"max_height",
	"long max_height(void)",
	max_height},
	{"glOrtho",
	"void glOrtho( GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat near_val, GLfloat far_val )",
	glOrtho6f},
