/*
 * MachUser.c - wrapper for mach_excUser.c
 *
 * Copyright (c) 2013 ARAnyM dev team (see AUTHORS)
 *
 * This file is part of the ARAnyM project which builds a new and powerful
 * TOS/FreeMiNT compatible virtual machine running on almost any hardware.
 *
 * ARAnyM is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * ARAnyM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ARAnyM; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * Last modified: 2013-06-16 Jens Heitmann
 *
 */

/*
 *
 * This is only a wrapper file, because generated code is x86_64 bit only and
 * will not build on a 32 bit target
 *
 */

#ifdef CPU_x86_64
// mach_excUser.c is generated by gen_machfiles for 64 bit targets
#include "mach_excUser.c"
#endif
