/* Generated by dispatch-gen.pl from /usr/local/include/GL/gl.h */

		case NFOSMESA_GLCLEARINDEX:
			nfglClearIndex((GLfloat)getStackedFloat(0));
			break;
		case NFOSMESA_GLCLEARCOLOR:
			nfglClearColor((GLclampf)getStackedFloat(0),(GLclampf)getStackedFloat(1),(GLclampf)getStackedFloat(2),(GLclampf)getStackedFloat(3));
			break;
		case NFOSMESA_GLCLEAR:
			nfglClear(getStackedParameter(0));
			break;
		case NFOSMESA_GLINDEXMASK:
			nfglIndexMask(getStackedParameter(0));
			break;
		case NFOSMESA_GLCOLORMASK:
			nfglColorMask(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLALPHAFUNC:
			nfglAlphaFunc(getStackedParameter(0),(GLclampf)getStackedFloat(1));
			break;
		case NFOSMESA_GLBLENDFUNC:
			nfglBlendFunc(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLLOGICOP:
			nfglLogicOp(getStackedParameter(0));
			break;
		case NFOSMESA_GLCULLFACE:
			nfglCullFace(getStackedParameter(0));
			break;
		case NFOSMESA_GLFRONTFACE:
			nfglFrontFace(getStackedParameter(0));
			break;
		case NFOSMESA_GLPOINTSIZE:
			nfglPointSize((GLfloat)getStackedFloat(0));
			break;
		case NFOSMESA_GLLINEWIDTH:
			nfglLineWidth((GLfloat)getStackedFloat(0));
			break;
		case NFOSMESA_GLLINESTIPPLE:
			nfglLineStipple(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLPOLYGONMODE:
			nfglPolygonMode(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLPOLYGONOFFSET:
			nfglPolygonOffset((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1));
			break;
		case NFOSMESA_GLPOLYGONSTIPPLE:
			nfglPolygonStipple((const GLubyte *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLGETPOLYGONSTIPPLE:
			nfglGetPolygonStipple((GLubyte *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLEDGEFLAG:
			nfglEdgeFlag(getStackedParameter(0));
			break;
		case NFOSMESA_GLEDGEFLAGV:
			nfglEdgeFlagv((const GLboolean *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLSCISSOR:
			nfglScissor(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLCLIPPLANE:
			nfglClipPlane(getStackedParameter(0),(const GLdouble *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLGETCLIPPLANE:
			nfglGetClipPlane(getStackedParameter(0),(GLdouble *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLDRAWBUFFER:
			nfglDrawBuffer(getStackedParameter(0));
			break;
		case NFOSMESA_GLREADBUFFER:
			nfglReadBuffer(getStackedParameter(0));
			break;
		case NFOSMESA_GLENABLE:
			nfglEnable(getStackedParameter(0));
			break;
		case NFOSMESA_GLDISABLE:
			nfglDisable(getStackedParameter(0));
			break;
		case NFOSMESA_GLISENABLED:
			ret = nfglIsEnabled(getStackedParameter(0));
			break;
		case NFOSMESA_GLENABLECLIENTSTATE:
			nfglEnableClientState(getStackedParameter(0)); /* 1.1 */
			break;
		case NFOSMESA_GLDISABLECLIENTSTATE:
			nfglDisableClientState(getStackedParameter(0)); /* 1.1 */
			break;
		case NFOSMESA_GLGETBOOLEANV:
			nfglGetBooleanv(getStackedParameter(0),(GLboolean *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLGETDOUBLEV:
			nfglGetDoublev(getStackedParameter(0),(GLdouble *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLGETFLOATV:
			nfglGetFloatv(getStackedParameter(0),(GLfloat *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLGETINTEGERV:
			nfglGetIntegerv(getStackedParameter(0),(GLint *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLPUSHATTRIB:
			nfglPushAttrib(getStackedParameter(0));
			break;
		case NFOSMESA_GLPOPATTRIB:
			nfglPopAttrib();
			break;
		case NFOSMESA_GLPUSHCLIENTATTRIB:
			nfglPushClientAttrib(getStackedParameter(0)); /* 1.1 */
			break;
		case NFOSMESA_GLPOPCLIENTATTRIB:
			nfglPopClientAttrib(); /* 1.1 */
			break;
		case NFOSMESA_GLRENDERMODE:
			ret = nfglRenderMode(getStackedParameter(0));
			break;
		case NFOSMESA_GLGETERROR:
			ret = nfglGetError();
			break;
/*
		case NFOSMESA_GLGETSTRING:
			ret = nfglGetString(getStackedParameter(0));
			break;
*/
		case NFOSMESA_GLFINISH:
			nfglFinish();
			break;
		case NFOSMESA_GLFLUSH:
			nfglFlush();
			break;
		case NFOSMESA_GLHINT:
			nfglHint(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLCLEARDEPTH:
			nfglClearDepth((GLclampd)Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)));
			break;
		case NFOSMESA_GLDEPTHFUNC:
			nfglDepthFunc(getStackedParameter(0));
			break;
		case NFOSMESA_GLDEPTHMASK:
			nfglDepthMask(getStackedParameter(0));
			break;
		case NFOSMESA_GLDEPTHRANGE:
			nfglDepthRange((GLclampd)Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),(GLclampd)Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)));
			break;
		case NFOSMESA_GLCLEARACCUM:
			nfglClearAccum((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2),(GLfloat)getStackedFloat(3));
			break;
		case NFOSMESA_GLACCUM:
			nfglAccum(getStackedParameter(0),(GLfloat)getStackedFloat(1));
			break;
		case NFOSMESA_GLMATRIXMODE:
			nfglMatrixMode(getStackedParameter(0));
			break;
		case NFOSMESA_GLORTHO:
			nfglOrtho(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)),Atari2HostDouble(getStackedParameter(4),getStackedParameter(5)),Atari2HostDouble(getStackedParameter(6),getStackedParameter(7)),Atari2HostDouble(getStackedParameter(8),getStackedParameter(9)),Atari2HostDouble(getStackedParameter(10),getStackedParameter(11)));
			break;
		case NFOSMESA_GLFRUSTUM:
			nfglFrustum(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)),Atari2HostDouble(getStackedParameter(4),getStackedParameter(5)),Atari2HostDouble(getStackedParameter(6),getStackedParameter(7)),Atari2HostDouble(getStackedParameter(8),getStackedParameter(9)),Atari2HostDouble(getStackedParameter(10),getStackedParameter(11)));
			break;
		case NFOSMESA_GLVIEWPORT:
			nfglViewport(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLPUSHMATRIX:
			nfglPushMatrix();
			break;
		case NFOSMESA_GLPOPMATRIX:
			nfglPopMatrix();
			break;
		case NFOSMESA_GLLOADIDENTITY:
			nfglLoadIdentity();
			break;
		case NFOSMESA_GLLOADMATRIXD:
			nfglLoadMatrixd((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLLOADMATRIXF:
			nfglLoadMatrixf((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLMULTMATRIXD:
			nfglMultMatrixd((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLMULTMATRIXF:
			nfglMultMatrixf((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLROTATED:
			nfglRotated(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)),Atari2HostDouble(getStackedParameter(4),getStackedParameter(5)),Atari2HostDouble(getStackedParameter(6),getStackedParameter(7)));
			break;
		case NFOSMESA_GLROTATEF:
			nfglRotatef((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2),(GLfloat)getStackedFloat(3));
			break;
		case NFOSMESA_GLSCALED:
			nfglScaled(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)),Atari2HostDouble(getStackedParameter(4),getStackedParameter(5)));
			break;
		case NFOSMESA_GLSCALEF:
			nfglScalef((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2));
			break;
		case NFOSMESA_GLTRANSLATED:
			nfglTranslated(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)),Atari2HostDouble(getStackedParameter(4),getStackedParameter(5)));
			break;
		case NFOSMESA_GLTRANSLATEF:
			nfglTranslatef((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2));
			break;
		case NFOSMESA_GLISLIST:
			ret = nfglIsList(getStackedParameter(0));
			break;
		case NFOSMESA_GLDELETELISTS:
			nfglDeleteLists(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLGENLISTS:
			ret = nfglGenLists(getStackedParameter(0));
			break;
		case NFOSMESA_GLNEWLIST:
			nfglNewList(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLENDLIST:
			nfglEndList();
			break;
		case NFOSMESA_GLCALLLIST:
			nfglCallList(getStackedParameter(0));
			break;
		case NFOSMESA_GLCALLLISTS:
			nfglCallLists(getStackedParameter(0),getStackedParameter(1),(const GLvoid *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLLISTBASE:
			nfglListBase(getStackedParameter(0));
			break;
		case NFOSMESA_GLBEGIN:
			nfglBegin(getStackedParameter(0));
			break;
		case NFOSMESA_GLEND:
			nfglEnd();
			break;
		case NFOSMESA_GLVERTEX2D:
			nfglVertex2d(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)));
			break;
		case NFOSMESA_GLVERTEX2F:
			nfglVertex2f((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1));
			break;
		case NFOSMESA_GLVERTEX2I:
			nfglVertex2i(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLVERTEX2S:
			nfglVertex2s(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLVERTEX3D:
			nfglVertex3d(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)),Atari2HostDouble(getStackedParameter(4),getStackedParameter(5)));
			break;
		case NFOSMESA_GLVERTEX3F:
			nfglVertex3f((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2));
			break;
		case NFOSMESA_GLVERTEX3I:
			nfglVertex3i(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLVERTEX3S:
			nfglVertex3s(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLVERTEX4D:
			nfglVertex4d(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)),Atari2HostDouble(getStackedParameter(4),getStackedParameter(5)),Atari2HostDouble(getStackedParameter(6),getStackedParameter(7)));
			break;
		case NFOSMESA_GLVERTEX4F:
			nfglVertex4f((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2),(GLfloat)getStackedFloat(3));
			break;
		case NFOSMESA_GLVERTEX4I:
			nfglVertex4i(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLVERTEX4S:
			nfglVertex4s(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLVERTEX2DV:
			nfglVertex2dv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLVERTEX2FV:
			nfglVertex2fv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLVERTEX2IV:
			nfglVertex2iv((const GLint *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLVERTEX2SV:
			nfglVertex2sv((const GLshort *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLVERTEX3DV:
			nfglVertex3dv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLVERTEX3FV:
			nfglVertex3fv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLVERTEX3IV:
			nfglVertex3iv((const GLint *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLVERTEX3SV:
			nfglVertex3sv((const GLshort *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLVERTEX4DV:
			nfglVertex4dv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLVERTEX4FV:
			nfglVertex4fv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLVERTEX4IV:
			nfglVertex4iv((const GLint *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLVERTEX4SV:
			nfglVertex4sv((const GLshort *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLNORMAL3B:
			nfglNormal3b(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLNORMAL3D:
			nfglNormal3d(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)),Atari2HostDouble(getStackedParameter(4),getStackedParameter(5)));
			break;
		case NFOSMESA_GLNORMAL3F:
			nfglNormal3f((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2));
			break;
		case NFOSMESA_GLNORMAL3I:
			nfglNormal3i(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLNORMAL3S:
			nfglNormal3s(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLNORMAL3BV:
			nfglNormal3bv((const GLbyte *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLNORMAL3DV:
			nfglNormal3dv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLNORMAL3FV:
			nfglNormal3fv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLNORMAL3IV:
			nfglNormal3iv((const GLint *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLNORMAL3SV:
			nfglNormal3sv((const GLshort *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLINDEXD:
			nfglIndexd(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)));
			break;
		case NFOSMESA_GLINDEXF:
			nfglIndexf((GLfloat)getStackedFloat(0));
			break;
		case NFOSMESA_GLINDEXI:
			nfglIndexi(getStackedParameter(0));
			break;
		case NFOSMESA_GLINDEXS:
			nfglIndexs(getStackedParameter(0));
			break;
		case NFOSMESA_GLINDEXUB:
			nfglIndexub(getStackedParameter(0)); /* 1.1 */
			break;
		case NFOSMESA_GLINDEXDV:
			nfglIndexdv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLINDEXFV:
			nfglIndexfv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLINDEXIV:
			nfglIndexiv((const GLint *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLINDEXSV:
			nfglIndexsv((const GLshort *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLINDEXUBV:
			nfglIndexubv((const GLubyte *)Atari2HostAddr(getStackedParameter(0))); /* 1.1 */
			break;
		case NFOSMESA_GLCOLOR3B:
			nfglColor3b(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLCOLOR3D:
			nfglColor3d(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)),Atari2HostDouble(getStackedParameter(4),getStackedParameter(5)));
			break;
		case NFOSMESA_GLCOLOR3F:
			nfglColor3f((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2));
			break;
		case NFOSMESA_GLCOLOR3I:
			nfglColor3i(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLCOLOR3S:
			nfglColor3s(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLCOLOR3UB:
			nfglColor3ub(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLCOLOR3UI:
			nfglColor3ui(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLCOLOR3US:
			nfglColor3us(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLCOLOR4B:
			nfglColor4b(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLCOLOR4D:
			nfglColor4d(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)),Atari2HostDouble(getStackedParameter(4),getStackedParameter(5)),Atari2HostDouble(getStackedParameter(6),getStackedParameter(7)));
			break;
		case NFOSMESA_GLCOLOR4F:
			nfglColor4f((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2),(GLfloat)getStackedFloat(3));
			break;
		case NFOSMESA_GLCOLOR4I:
			nfglColor4i(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLCOLOR4S:
			nfglColor4s(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLCOLOR4UB:
			nfglColor4ub(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLCOLOR4UI:
			nfglColor4ui(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLCOLOR4US:
			nfglColor4us(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLCOLOR3BV:
			nfglColor3bv((const GLbyte *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLCOLOR3DV:
			nfglColor3dv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLCOLOR3FV:
			nfglColor3fv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLCOLOR3IV:
			nfglColor3iv((const GLint *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLCOLOR3SV:
			nfglColor3sv((const GLshort *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLCOLOR3UBV:
			nfglColor3ubv((const GLubyte *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLCOLOR3UIV:
			nfglColor3uiv((const GLuint *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLCOLOR3USV:
			nfglColor3usv((const GLushort *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLCOLOR4BV:
			nfglColor4bv((const GLbyte *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLCOLOR4DV:
			nfglColor4dv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLCOLOR4FV:
			nfglColor4fv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLCOLOR4IV:
			nfglColor4iv((const GLint *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLCOLOR4SV:
			nfglColor4sv((const GLshort *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLCOLOR4UBV:
			nfglColor4ubv((const GLubyte *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLCOLOR4UIV:
			nfglColor4uiv((const GLuint *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLCOLOR4USV:
			nfglColor4usv((const GLushort *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTEXCOORD1D:
			nfglTexCoord1d(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD1F:
			nfglTexCoord1f((GLfloat)getStackedFloat(0));
			break;
		case NFOSMESA_GLTEXCOORD1I:
			nfglTexCoord1i(getStackedParameter(0));
			break;
		case NFOSMESA_GLTEXCOORD1S:
			nfglTexCoord1s(getStackedParameter(0));
			break;
		case NFOSMESA_GLTEXCOORD2D:
			nfglTexCoord2d(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)));
			break;
		case NFOSMESA_GLTEXCOORD2F:
			nfglTexCoord2f((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1));
			break;
		case NFOSMESA_GLTEXCOORD2I:
			nfglTexCoord2i(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLTEXCOORD2S:
			nfglTexCoord2s(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLTEXCOORD3D:
			nfglTexCoord3d(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)),Atari2HostDouble(getStackedParameter(4),getStackedParameter(5)));
			break;
		case NFOSMESA_GLTEXCOORD3F:
			nfglTexCoord3f((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2));
			break;
		case NFOSMESA_GLTEXCOORD3I:
			nfglTexCoord3i(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLTEXCOORD3S:
			nfglTexCoord3s(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLTEXCOORD4D:
			nfglTexCoord4d(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)),Atari2HostDouble(getStackedParameter(4),getStackedParameter(5)),Atari2HostDouble(getStackedParameter(6),getStackedParameter(7)));
			break;
		case NFOSMESA_GLTEXCOORD4F:
			nfglTexCoord4f((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2),(GLfloat)getStackedFloat(3));
			break;
		case NFOSMESA_GLTEXCOORD4I:
			nfglTexCoord4i(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLTEXCOORD4S:
			nfglTexCoord4s(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLTEXCOORD1DV:
			nfglTexCoord1dv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTEXCOORD1FV:
			nfglTexCoord1fv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTEXCOORD1IV:
			nfglTexCoord1iv((const GLint *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTEXCOORD1SV:
			nfglTexCoord1sv((const GLshort *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTEXCOORD2DV:
			nfglTexCoord2dv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTEXCOORD2FV:
			nfglTexCoord2fv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTEXCOORD2IV:
			nfglTexCoord2iv((const GLint *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTEXCOORD2SV:
			nfglTexCoord2sv((const GLshort *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTEXCOORD3DV:
			nfglTexCoord3dv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTEXCOORD3FV:
			nfglTexCoord3fv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTEXCOORD3IV:
			nfglTexCoord3iv((const GLint *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTEXCOORD3SV:
			nfglTexCoord3sv((const GLshort *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTEXCOORD4DV:
			nfglTexCoord4dv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTEXCOORD4FV:
			nfglTexCoord4fv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTEXCOORD4IV:
			nfglTexCoord4iv((const GLint *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTEXCOORD4SV:
			nfglTexCoord4sv((const GLshort *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLRASTERPOS2D:
			nfglRasterPos2d(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)));
			break;
		case NFOSMESA_GLRASTERPOS2F:
			nfglRasterPos2f((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1));
			break;
		case NFOSMESA_GLRASTERPOS2I:
			nfglRasterPos2i(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLRASTERPOS2S:
			nfglRasterPos2s(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLRASTERPOS3D:
			nfglRasterPos3d(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)),Atari2HostDouble(getStackedParameter(4),getStackedParameter(5)));
			break;
		case NFOSMESA_GLRASTERPOS3F:
			nfglRasterPos3f((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2));
			break;
		case NFOSMESA_GLRASTERPOS3I:
			nfglRasterPos3i(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLRASTERPOS3S:
			nfglRasterPos3s(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLRASTERPOS4D:
			nfglRasterPos4d(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)),Atari2HostDouble(getStackedParameter(4),getStackedParameter(5)),Atari2HostDouble(getStackedParameter(6),getStackedParameter(7)));
			break;
		case NFOSMESA_GLRASTERPOS4F:
			nfglRasterPos4f((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2),(GLfloat)getStackedFloat(3));
			break;
		case NFOSMESA_GLRASTERPOS4I:
			nfglRasterPos4i(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLRASTERPOS4S:
			nfglRasterPos4s(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLRASTERPOS2DV:
			nfglRasterPos2dv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLRASTERPOS2FV:
			nfglRasterPos2fv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLRASTERPOS2IV:
			nfglRasterPos2iv((const GLint *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLRASTERPOS2SV:
			nfglRasterPos2sv((const GLshort *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLRASTERPOS3DV:
			nfglRasterPos3dv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLRASTERPOS3FV:
			nfglRasterPos3fv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLRASTERPOS3IV:
			nfglRasterPos3iv((const GLint *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLRASTERPOS3SV:
			nfglRasterPos3sv((const GLshort *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLRASTERPOS4DV:
			nfglRasterPos4dv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLRASTERPOS4FV:
			nfglRasterPos4fv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLRASTERPOS4IV:
			nfglRasterPos4iv((const GLint *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLRASTERPOS4SV:
			nfglRasterPos4sv((const GLshort *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLRECTD:
			nfglRectd(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)),Atari2HostDouble(getStackedParameter(4),getStackedParameter(5)),Atari2HostDouble(getStackedParameter(6),getStackedParameter(7)));
			break;
		case NFOSMESA_GLRECTF:
			nfglRectf((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2),(GLfloat)getStackedFloat(3));
			break;
		case NFOSMESA_GLRECTI:
			nfglRecti(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLRECTS:
			nfglRects(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLRECTDV:
			nfglRectdv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)),(const GLdouble *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLRECTFV:
			nfglRectfv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)),(const GLfloat *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLRECTIV:
			nfglRectiv((const GLint *)Atari2HostAddr(getStackedParameter(0)),(const GLint *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLRECTSV:
			nfglRectsv((const GLshort *)Atari2HostAddr(getStackedParameter(0)),(const GLshort *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLVERTEXPOINTER:
			nfglVertexPointer(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),(const GLvoid *)Atari2HostAddr(getStackedParameter(3)));
			break;
		case NFOSMESA_GLNORMALPOINTER:
			nfglNormalPointer(getStackedParameter(0),getStackedParameter(1),(const GLvoid *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLCOLORPOINTER:
			nfglColorPointer(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),(const GLvoid *)Atari2HostAddr(getStackedParameter(3)));
			break;
		case NFOSMESA_GLINDEXPOINTER:
			nfglIndexPointer(getStackedParameter(0),getStackedParameter(1),(const GLvoid *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLTEXCOORDPOINTER:
			nfglTexCoordPointer(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),(const GLvoid *)Atari2HostAddr(getStackedParameter(3)));
			break;
		case NFOSMESA_GLEDGEFLAGPOINTER:
			nfglEdgeFlagPointer(getStackedParameter(0),(const GLvoid *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLGETPOINTERV:
			nfglGetPointerv(getStackedParameter(0),(GLvoid **)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLARRAYELEMENT:
			nfglArrayElement(getStackedParameter(0));
			break;
		case NFOSMESA_GLDRAWARRAYS:
			nfglDrawArrays(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLDRAWELEMENTS:
			nfglDrawElements(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),(const GLvoid *)Atari2HostAddr(getStackedParameter(3)));
			break;
		case NFOSMESA_GLINTERLEAVEDARRAYS:
			nfglInterleavedArrays(getStackedParameter(0),getStackedParameter(1),(const GLvoid *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLSHADEMODEL:
			nfglShadeModel(getStackedParameter(0));
			break;
		case NFOSMESA_GLLIGHTF:
			nfglLightf(getStackedParameter(0),getStackedParameter(1),(GLfloat)getStackedFloat(2));
			break;
		case NFOSMESA_GLLIGHTI:
			nfglLighti(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLLIGHTFV:
			nfglLightfv(getStackedParameter(0),getStackedParameter(1),(const GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLLIGHTIV:
			nfglLightiv(getStackedParameter(0),getStackedParameter(1),(const GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETLIGHTFV:
			nfglGetLightfv(getStackedParameter(0),getStackedParameter(1),(GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETLIGHTIV:
			nfglGetLightiv(getStackedParameter(0),getStackedParameter(1),(GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLLIGHTMODELF:
			nfglLightModelf(getStackedParameter(0),(GLfloat)getStackedFloat(1));
			break;
		case NFOSMESA_GLLIGHTMODELI:
			nfglLightModeli(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLLIGHTMODELFV:
			nfglLightModelfv(getStackedParameter(0),(const GLfloat *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLLIGHTMODELIV:
			nfglLightModeliv(getStackedParameter(0),(const GLint *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMATERIALF:
			nfglMaterialf(getStackedParameter(0),getStackedParameter(1),(GLfloat)getStackedFloat(2));
			break;
		case NFOSMESA_GLMATERIALI:
			nfglMateriali(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLMATERIALFV:
			nfglMaterialfv(getStackedParameter(0),getStackedParameter(1),(const GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLMATERIALIV:
			nfglMaterialiv(getStackedParameter(0),getStackedParameter(1),(const GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETMATERIALFV:
			nfglGetMaterialfv(getStackedParameter(0),getStackedParameter(1),(GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETMATERIALIV:
			nfglGetMaterialiv(getStackedParameter(0),getStackedParameter(1),(GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLCOLORMATERIAL:
			nfglColorMaterial(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLPIXELZOOM:
			nfglPixelZoom((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1));
			break;
		case NFOSMESA_GLPIXELSTOREF:
			nfglPixelStoref(getStackedParameter(0),(GLfloat)getStackedFloat(1));
			break;
		case NFOSMESA_GLPIXELSTOREI:
			nfglPixelStorei(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLPIXELTRANSFERF:
			nfglPixelTransferf(getStackedParameter(0),(GLfloat)getStackedFloat(1));
			break;
		case NFOSMESA_GLPIXELTRANSFERI:
			nfglPixelTransferi(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLPIXELMAPFV:
			nfglPixelMapfv(getStackedParameter(0),getStackedParameter(1),(const GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLPIXELMAPUIV:
			nfglPixelMapuiv(getStackedParameter(0),getStackedParameter(1),(const GLuint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLPIXELMAPUSV:
			nfglPixelMapusv(getStackedParameter(0),getStackedParameter(1),(const GLushort *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETPIXELMAPFV:
			nfglGetPixelMapfv(getStackedParameter(0),(GLfloat *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLGETPIXELMAPUIV:
			nfglGetPixelMapuiv(getStackedParameter(0),(GLuint *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLGETPIXELMAPUSV:
			nfglGetPixelMapusv(getStackedParameter(0),(GLushort *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLBITMAP:
			nfglBitmap(getStackedParameter(0),getStackedParameter(1),(GLfloat)getStackedFloat(2),(GLfloat)getStackedFloat(3),(GLfloat)getStackedFloat(4),(GLfloat)getStackedFloat(5),(const GLubyte *)Atari2HostAddr(getStackedParameter(6)));
			break;
		case NFOSMESA_GLREADPIXELS:
			nfglReadPixels(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),(GLvoid *)Atari2HostAddr(getStackedParameter(6)));
			break;
		case NFOSMESA_GLDRAWPIXELS:
			nfglDrawPixels(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),(const GLvoid *)Atari2HostAddr(getStackedParameter(4)));
			break;
		case NFOSMESA_GLCOPYPIXELS:
			nfglCopyPixels(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4));
			break;
		case NFOSMESA_GLSTENCILFUNC:
			nfglStencilFunc(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLSTENCILMASK:
			nfglStencilMask(getStackedParameter(0));
			break;
		case NFOSMESA_GLSTENCILOP:
			nfglStencilOp(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLCLEARSTENCIL:
			nfglClearStencil(getStackedParameter(0));
			break;
		case NFOSMESA_GLTEXGEND:
			nfglTexGend(getStackedParameter(0),getStackedParameter(1),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)));
			break;
		case NFOSMESA_GLTEXGENF:
			nfglTexGenf(getStackedParameter(0),getStackedParameter(1),(GLfloat)getStackedFloat(2));
			break;
		case NFOSMESA_GLTEXGENI:
			nfglTexGeni(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLTEXGENDV:
			nfglTexGendv(getStackedParameter(0),getStackedParameter(1),(const GLdouble *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLTEXGENFV:
			nfglTexGenfv(getStackedParameter(0),getStackedParameter(1),(const GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLTEXGENIV:
			nfglTexGeniv(getStackedParameter(0),getStackedParameter(1),(const GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETTEXGENDV:
			nfglGetTexGendv(getStackedParameter(0),getStackedParameter(1),(GLdouble *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETTEXGENFV:
			nfglGetTexGenfv(getStackedParameter(0),getStackedParameter(1),(GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETTEXGENIV:
			nfglGetTexGeniv(getStackedParameter(0),getStackedParameter(1),(GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLTEXENVF:
			nfglTexEnvf(getStackedParameter(0),getStackedParameter(1),(GLfloat)getStackedFloat(2));
			break;
		case NFOSMESA_GLTEXENVI:
			nfglTexEnvi(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLTEXENVFV:
			nfglTexEnvfv(getStackedParameter(0),getStackedParameter(1),(const GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLTEXENVIV:
			nfglTexEnviv(getStackedParameter(0),getStackedParameter(1),(const GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETTEXENVFV:
			nfglGetTexEnvfv(getStackedParameter(0),getStackedParameter(1),(GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETTEXENVIV:
			nfglGetTexEnviv(getStackedParameter(0),getStackedParameter(1),(GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLTEXPARAMETERF:
			nfglTexParameterf(getStackedParameter(0),getStackedParameter(1),(GLfloat)getStackedFloat(2));
			break;
		case NFOSMESA_GLTEXPARAMETERI:
			nfglTexParameteri(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLTEXPARAMETERFV:
			nfglTexParameterfv(getStackedParameter(0),getStackedParameter(1),(const GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLTEXPARAMETERIV:
			nfglTexParameteriv(getStackedParameter(0),getStackedParameter(1),(const GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETTEXPARAMETERFV:
			nfglGetTexParameterfv(getStackedParameter(0),getStackedParameter(1),(GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETTEXPARAMETERIV:
			nfglGetTexParameteriv(getStackedParameter(0),getStackedParameter(1),(GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETTEXLEVELPARAMETERFV:
			nfglGetTexLevelParameterfv(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),(GLfloat *)Atari2HostAddr(getStackedParameter(3)));
			break;
		case NFOSMESA_GLGETTEXLEVELPARAMETERIV:
			nfglGetTexLevelParameteriv(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),(GLint *)Atari2HostAddr(getStackedParameter(3)));
			break;
		case NFOSMESA_GLTEXIMAGE1D:
			nfglTexImage1D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),getStackedParameter(6),(const GLvoid *)Atari2HostAddr(getStackedParameter(7)));
			break;
		case NFOSMESA_GLTEXIMAGE2D:
			nfglTexImage2D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),getStackedParameter(6),getStackedParameter(7),(const GLvoid *)Atari2HostAddr(getStackedParameter(8)));
			break;
		case NFOSMESA_GLGETTEXIMAGE:
			nfglGetTexImage(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),(GLvoid *)Atari2HostAddr(getStackedParameter(4)));
			break;
		case NFOSMESA_GLGENTEXTURES:
			nfglGenTextures(getStackedParameter(0),(GLuint *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLDELETETEXTURES:
			nfglDeleteTextures(getStackedParameter(0),(const GLuint *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLBINDTEXTURE:
			nfglBindTexture(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLPRIORITIZETEXTURES:
			nfglPrioritizeTextures(getStackedParameter(0),(const GLuint *)Atari2HostAddr(getStackedParameter(1)),(const GLclampf *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLARETEXTURESRESIDENT:
			ret = nfglAreTexturesResident(getStackedParameter(0),(const GLuint *)Atari2HostAddr(getStackedParameter(1)),(GLboolean *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLISTEXTURE:
			ret = nfglIsTexture(getStackedParameter(0));
			break;
		case NFOSMESA_GLTEXSUBIMAGE1D:
			nfglTexSubImage1D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),(const GLvoid *)Atari2HostAddr(getStackedParameter(6)));
			break;
		case NFOSMESA_GLTEXSUBIMAGE2D:
			nfglTexSubImage2D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),getStackedParameter(6),getStackedParameter(7),(const GLvoid *)Atari2HostAddr(getStackedParameter(8)));
			break;
		case NFOSMESA_GLCOPYTEXIMAGE1D:
			nfglCopyTexImage1D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),getStackedParameter(6));
			break;
		case NFOSMESA_GLCOPYTEXIMAGE2D:
			nfglCopyTexImage2D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),getStackedParameter(6),getStackedParameter(7));
			break;
		case NFOSMESA_GLCOPYTEXSUBIMAGE1D:
			nfglCopyTexSubImage1D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5));
			break;
		case NFOSMESA_GLCOPYTEXSUBIMAGE2D:
			nfglCopyTexSubImage2D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),getStackedParameter(6),getStackedParameter(7));
			break;
		case NFOSMESA_GLMAP1D:
			nfglMap1d(getStackedParameter(0),Atari2HostDouble(getStackedParameter(1),getStackedParameter(2)),Atari2HostDouble(getStackedParameter(3),getStackedParameter(4)),getStackedParameter(5),getStackedParameter(6),(const GLdouble *)Atari2HostAddr(getStackedParameter(7)));
			break;
		case NFOSMESA_GLMAP1F:
			nfglMap1f(getStackedParameter(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2),getStackedParameter(3),getStackedParameter(4),(const GLfloat *)Atari2HostAddr(getStackedParameter(5)));
			break;
		case NFOSMESA_GLMAP2D:
			nfglMap2d(getStackedParameter(0),Atari2HostDouble(getStackedParameter(1),getStackedParameter(2)),Atari2HostDouble(getStackedParameter(3),getStackedParameter(4)),getStackedParameter(5),getStackedParameter(6),Atari2HostDouble(getStackedParameter(7),getStackedParameter(8)),Atari2HostDouble(getStackedParameter(9),getStackedParameter(10)),getStackedParameter(11),getStackedParameter(12),(const GLdouble *)Atari2HostAddr(getStackedParameter(13)));
			break;
		case NFOSMESA_GLMAP2F:
			nfglMap2f(getStackedParameter(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2),getStackedParameter(3),getStackedParameter(4),(GLfloat)getStackedFloat(5),(GLfloat)getStackedFloat(6),getStackedParameter(7),getStackedParameter(8),(const GLfloat *)Atari2HostAddr(getStackedParameter(9)));
			break;
		case NFOSMESA_GLGETMAPDV:
			nfglGetMapdv(getStackedParameter(0),getStackedParameter(1),(GLdouble *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETMAPFV:
			nfglGetMapfv(getStackedParameter(0),getStackedParameter(1),(GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETMAPIV:
			nfglGetMapiv(getStackedParameter(0),getStackedParameter(1),(GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLEVALCOORD1D:
			nfglEvalCoord1d(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)));
			break;
		case NFOSMESA_GLEVALCOORD1F:
			nfglEvalCoord1f((GLfloat)getStackedFloat(0));
			break;
		case NFOSMESA_GLEVALCOORD1DV:
			nfglEvalCoord1dv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLEVALCOORD1FV:
			nfglEvalCoord1fv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLEVALCOORD2D:
			nfglEvalCoord2d(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)),Atari2HostDouble(getStackedParameter(2),getStackedParameter(3)));
			break;
		case NFOSMESA_GLEVALCOORD2F:
			nfglEvalCoord2f((GLfloat)getStackedFloat(0),(GLfloat)getStackedFloat(1));
			break;
		case NFOSMESA_GLEVALCOORD2DV:
			nfglEvalCoord2dv((const GLdouble *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLEVALCOORD2FV:
			nfglEvalCoord2fv((const GLfloat *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLMAPGRID1D:
			nfglMapGrid1d(getStackedParameter(0),Atari2HostDouble(getStackedParameter(1),getStackedParameter(2)),Atari2HostDouble(getStackedParameter(3),getStackedParameter(4)));
			break;
		case NFOSMESA_GLMAPGRID1F:
			nfglMapGrid1f(getStackedParameter(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2));
			break;
		case NFOSMESA_GLMAPGRID2D:
			nfglMapGrid2d(getStackedParameter(0),Atari2HostDouble(getStackedParameter(1),getStackedParameter(2)),Atari2HostDouble(getStackedParameter(3),getStackedParameter(4)),getStackedParameter(5),Atari2HostDouble(getStackedParameter(6),getStackedParameter(7)),Atari2HostDouble(getStackedParameter(8),getStackedParameter(9)));
			break;
		case NFOSMESA_GLMAPGRID2F:
			nfglMapGrid2f(getStackedParameter(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2),getStackedParameter(3),(GLfloat)getStackedFloat(4),(GLfloat)getStackedFloat(5));
			break;
		case NFOSMESA_GLEVALPOINT1:
			nfglEvalPoint1(getStackedParameter(0));
			break;
		case NFOSMESA_GLEVALPOINT2:
			nfglEvalPoint2(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLEVALMESH1:
			nfglEvalMesh1(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLEVALMESH2:
			nfglEvalMesh2(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4));
			break;
		case NFOSMESA_GLFOGF:
			nfglFogf(getStackedParameter(0),(GLfloat)getStackedFloat(1));
			break;
		case NFOSMESA_GLFOGI:
			nfglFogi(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLFOGFV:
			nfglFogfv(getStackedParameter(0),(const GLfloat *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLFOGIV:
			nfglFogiv(getStackedParameter(0),(const GLint *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLFEEDBACKBUFFER:
			nfglFeedbackBuffer(getStackedParameter(0),getStackedParameter(1),(GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLPASSTHROUGH:
			nfglPassThrough((GLfloat)getStackedFloat(0));
			break;
		case NFOSMESA_GLSELECTBUFFER:
			nfglSelectBuffer(getStackedParameter(0),(GLuint *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLINITNAMES:
			nfglInitNames();
			break;
		case NFOSMESA_GLLOADNAME:
			nfglLoadName(getStackedParameter(0));
			break;
		case NFOSMESA_GLPUSHNAME:
			nfglPushName(getStackedParameter(0));
			break;
		case NFOSMESA_GLPOPNAME:
			nfglPopName();
			break;
/*
		case NFOSMESA_GLDRAWRANGEELEMENTS:
			nfglDrawRangeElements(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),(const GLvoid *)Atari2HostAddr(getStackedParameter(5)));
			break;
		case NFOSMESA_GLTEXIMAGE3D:
			nfglTexImage3D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),getStackedParameter(6),getStackedParameter(7),getStackedParameter(8),(const GLvoid *)Atari2HostAddr(getStackedParameter(9)));
			break;
		case NFOSMESA_GLTEXSUBIMAGE3D:
			nfglTexSubImage3D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),getStackedParameter(6),getStackedParameter(7),getStackedParameter(8),getStackedParameter(9),(const GLvoid *)Atari2HostAddr(getStackedParameter(10)));
			break;
		case NFOSMESA_GLCOPYTEXSUBIMAGE3D:
			nfglCopyTexSubImage3D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),getStackedParameter(6),getStackedParameter(7),getStackedParameter(8));
			break;
		case NFOSMESA_GLCOLORTABLE:
			nfglColorTable(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),(const GLvoid *)Atari2HostAddr(getStackedParameter(5)));
			break;
		case NFOSMESA_GLCOLORSUBTABLE:
			nfglColorSubTable(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),(const GLvoid *)Atari2HostAddr(getStackedParameter(5)));
			break;
		case NFOSMESA_GLCOLORTABLEPARAMETERIV:
			nfglColorTableParameteriv(getStackedParameter(0),getStackedParameter(1),(const GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLCOLORTABLEPARAMETERFV:
			nfglColorTableParameterfv(getStackedParameter(0),getStackedParameter(1),(const GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLCOPYCOLORSUBTABLE:
			nfglCopyColorSubTable(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4));
			break;
		case NFOSMESA_GLCOPYCOLORTABLE:
			nfglCopyColorTable(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4));
			break;
		case NFOSMESA_GLGETCOLORTABLE:
			nfglGetColorTable(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),(GLvoid *)Atari2HostAddr(getStackedParameter(3)));
			break;
		case NFOSMESA_GLGETCOLORTABLEPARAMETERFV:
			nfglGetColorTableParameterfv(getStackedParameter(0),getStackedParameter(1),(GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETCOLORTABLEPARAMETERIV:
			nfglGetColorTableParameteriv(getStackedParameter(0),getStackedParameter(1),(GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLBLENDEQUATION:
			nfglBlendEquation(getStackedParameter(0));
			break;
		case NFOSMESA_GLBLENDCOLOR:
			nfglBlendColor((GLclampf)getStackedFloat(0),(GLclampf)getStackedFloat(1),(GLclampf)getStackedFloat(2),(GLclampf)getStackedFloat(3));
			break;
		case NFOSMESA_GLHISTOGRAM:
			nfglHistogram(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLRESETHISTOGRAM:
			nfglResetHistogram(getStackedParameter(0));
			break;
		case NFOSMESA_GLGETHISTOGRAM:
			nfglGetHistogram(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),(GLvoid *)Atari2HostAddr(getStackedParameter(4)));
			break;
		case NFOSMESA_GLGETHISTOGRAMPARAMETERFV:
			nfglGetHistogramParameterfv(getStackedParameter(0),getStackedParameter(1),(GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETHISTOGRAMPARAMETERIV:
			nfglGetHistogramParameteriv(getStackedParameter(0),getStackedParameter(1),(GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLMINMAX:
			nfglMinmax(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLRESETMINMAX:
			nfglResetMinmax(getStackedParameter(0));
			break;
		case NFOSMESA_GLGETMINMAX:
			nfglGetMinmax(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),(GLvoid *)Atari2HostAddr(getStackedParameter(4)));
			break;
		case NFOSMESA_GLGETMINMAXPARAMETERFV:
			nfglGetMinmaxParameterfv(getStackedParameter(0),getStackedParameter(1),(GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETMINMAXPARAMETERIV:
			nfglGetMinmaxParameteriv(getStackedParameter(0),getStackedParameter(1),(GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLCONVOLUTIONFILTER1D:
			nfglConvolutionFilter1D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),(const GLvoid *)Atari2HostAddr(getStackedParameter(5)));
			break;
		case NFOSMESA_GLCONVOLUTIONFILTER2D:
			nfglConvolutionFilter2D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),(const GLvoid *)Atari2HostAddr(getStackedParameter(6)));
			break;
		case NFOSMESA_GLCONVOLUTIONPARAMETERF:
			nfglConvolutionParameterf(getStackedParameter(0),getStackedParameter(1),(GLfloat)getStackedFloat(2));
			break;
		case NFOSMESA_GLCONVOLUTIONPARAMETERFV:
			nfglConvolutionParameterfv(getStackedParameter(0),getStackedParameter(1),(const GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLCONVOLUTIONPARAMETERI:
			nfglConvolutionParameteri(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLCONVOLUTIONPARAMETERIV:
			nfglConvolutionParameteriv(getStackedParameter(0),getStackedParameter(1),(const GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLCOPYCONVOLUTIONFILTER1D:
			nfglCopyConvolutionFilter1D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4));
			break;
		case NFOSMESA_GLCOPYCONVOLUTIONFILTER2D:
			nfglCopyConvolutionFilter2D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5));
			break;
		case NFOSMESA_GLGETCONVOLUTIONFILTER:
			nfglGetConvolutionFilter(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),(GLvoid *)Atari2HostAddr(getStackedParameter(3)));
			break;
		case NFOSMESA_GLGETCONVOLUTIONPARAMETERFV:
			nfglGetConvolutionParameterfv(getStackedParameter(0),getStackedParameter(1),(GLfloat *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLGETCONVOLUTIONPARAMETERIV:
			nfglGetConvolutionParameteriv(getStackedParameter(0),getStackedParameter(1),(GLint *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLSEPARABLEFILTER2D:
			nfglSeparableFilter2D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),(const GLvoid *)Atari2HostAddr(getStackedParameter(6)),(const GLvoid *)Atari2HostAddr(getStackedParameter(7)));
			break;
		case NFOSMESA_GLGETSEPARABLEFILTER:
			nfglGetSeparableFilter(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),(GLvoid *)Atari2HostAddr(getStackedParameter(3)),(GLvoid *)Atari2HostAddr(getStackedParameter(4)),(GLvoid *)Atari2HostAddr(getStackedParameter(5)));
			break;
		case NFOSMESA_GLACTIVETEXTURE:
			nfglActiveTexture(getStackedParameter(0));
			break;
		case NFOSMESA_GLCLIENTACTIVETEXTURE:
			nfglClientActiveTexture(getStackedParameter(0));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXIMAGE1D:
			nfglCompressedTexImage1D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),(const GLvoid *)Atari2HostAddr(getStackedParameter(6)));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXIMAGE2D:
			nfglCompressedTexImage2D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),getStackedParameter(6),(const GLvoid *)Atari2HostAddr(getStackedParameter(7)));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXIMAGE3D:
			nfglCompressedTexImage3D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),getStackedParameter(6),getStackedParameter(7),(const GLvoid *)Atari2HostAddr(getStackedParameter(8)));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXSUBIMAGE1D:
			nfglCompressedTexSubImage1D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),(const GLvoid *)Atari2HostAddr(getStackedParameter(6)));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXSUBIMAGE2D:
			nfglCompressedTexSubImage2D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),getStackedParameter(6),getStackedParameter(7),(const GLvoid *)Atari2HostAddr(getStackedParameter(8)));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXSUBIMAGE3D:
			nfglCompressedTexSubImage3D(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4),getStackedParameter(5),getStackedParameter(6),getStackedParameter(7),getStackedParameter(8),getStackedParameter(9),(const GLvoid *)Atari2HostAddr(getStackedParameter(10)));
			break;
		case NFOSMESA_GLGETCOMPRESSEDTEXIMAGE:
			nfglGetCompressedTexImage(getStackedParameter(0),getStackedParameter(1),(GLvoid *)Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1D:
			nfglMultiTexCoord1d(getStackedParameter(0),Atari2HostDouble(getStackedParameter(1),getStackedParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1DV:
			nfglMultiTexCoord1dv(getStackedParameter(0),(const GLdouble *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1F:
			nfglMultiTexCoord1f(getStackedParameter(0),(GLfloat)getStackedFloat(1));
			break;
		case NFOSMESA_GLMULTITEXCOORD1FV:
			nfglMultiTexCoord1fv(getStackedParameter(0),(const GLfloat *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1I:
			nfglMultiTexCoord1i(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLMULTITEXCOORD1IV:
			nfglMultiTexCoord1iv(getStackedParameter(0),(const GLint *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1S:
			nfglMultiTexCoord1s(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLMULTITEXCOORD1SV:
			nfglMultiTexCoord1sv(getStackedParameter(0),(const GLshort *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2D:
			nfglMultiTexCoord2d(getStackedParameter(0),Atari2HostDouble(getStackedParameter(1),getStackedParameter(2)),Atari2HostDouble(getStackedParameter(3),getStackedParameter(4)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2DV:
			nfglMultiTexCoord2dv(getStackedParameter(0),(const GLdouble *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2F:
			nfglMultiTexCoord2f(getStackedParameter(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2));
			break;
		case NFOSMESA_GLMULTITEXCOORD2FV:
			nfglMultiTexCoord2fv(getStackedParameter(0),(const GLfloat *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2I:
			nfglMultiTexCoord2i(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLMULTITEXCOORD2IV:
			nfglMultiTexCoord2iv(getStackedParameter(0),(const GLint *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2S:
			nfglMultiTexCoord2s(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLMULTITEXCOORD2SV:
			nfglMultiTexCoord2sv(getStackedParameter(0),(const GLshort *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3D:
			nfglMultiTexCoord3d(getStackedParameter(0),Atari2HostDouble(getStackedParameter(1),getStackedParameter(2)),Atari2HostDouble(getStackedParameter(3),getStackedParameter(4)),Atari2HostDouble(getStackedParameter(5),getStackedParameter(6)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3DV:
			nfglMultiTexCoord3dv(getStackedParameter(0),(const GLdouble *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3F:
			nfglMultiTexCoord3f(getStackedParameter(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2),(GLfloat)getStackedFloat(3));
			break;
		case NFOSMESA_GLMULTITEXCOORD3FV:
			nfglMultiTexCoord3fv(getStackedParameter(0),(const GLfloat *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3I:
			nfglMultiTexCoord3i(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLMULTITEXCOORD3IV:
			nfglMultiTexCoord3iv(getStackedParameter(0),(const GLint *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3S:
			nfglMultiTexCoord3s(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLMULTITEXCOORD3SV:
			nfglMultiTexCoord3sv(getStackedParameter(0),(const GLshort *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4D:
			nfglMultiTexCoord4d(getStackedParameter(0),Atari2HostDouble(getStackedParameter(1),getStackedParameter(2)),Atari2HostDouble(getStackedParameter(3),getStackedParameter(4)),Atari2HostDouble(getStackedParameter(5),getStackedParameter(6)),Atari2HostDouble(getStackedParameter(7),getStackedParameter(8)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4DV:
			nfglMultiTexCoord4dv(getStackedParameter(0),(const GLdouble *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4F:
			nfglMultiTexCoord4f(getStackedParameter(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2),(GLfloat)getStackedFloat(3),(GLfloat)getStackedFloat(4));
			break;
		case NFOSMESA_GLMULTITEXCOORD4FV:
			nfglMultiTexCoord4fv(getStackedParameter(0),(const GLfloat *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4I:
			nfglMultiTexCoord4i(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4));
			break;
		case NFOSMESA_GLMULTITEXCOORD4IV:
			nfglMultiTexCoord4iv(getStackedParameter(0),(const GLint *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4S:
			nfglMultiTexCoord4s(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4));
			break;
		case NFOSMESA_GLMULTITEXCOORD4SV:
			nfglMultiTexCoord4sv(getStackedParameter(0),(const GLshort *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLLOADTRANSPOSEMATRIXD:
			nfglLoadTransposeMatrixd(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)));
			break;
		case NFOSMESA_GLLOADTRANSPOSEMATRIXF:
			nfglLoadTransposeMatrixf((GLfloat)getStackedFloat(0));
			break;
		case NFOSMESA_GLMULTTRANSPOSEMATRIXD:
			nfglMultTransposeMatrixd(Atari2HostDouble(getStackedParameter(0),getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTTRANSPOSEMATRIXF:
			nfglMultTransposeMatrixf((GLfloat)getStackedFloat(0));
			break;
		case NFOSMESA_GLSAMPLECOVERAGE:
			nfglSampleCoverage((GLclampf)getStackedFloat(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLACTIVETEXTUREARB:
			nfglActiveTextureARB(getStackedParameter(0));
			break;
		case NFOSMESA_GLCLIENTACTIVETEXTUREARB:
			nfglClientActiveTextureARB(getStackedParameter(0));
			break;
		case NFOSMESA_GLMULTITEXCOORD1DARB:
			nfglMultiTexCoord1dARB(getStackedParameter(0),Atari2HostDouble(getStackedParameter(1),getStackedParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1DVARB:
			nfglMultiTexCoord1dvARB(getStackedParameter(0),(const GLdouble *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1FARB:
			nfglMultiTexCoord1fARB(getStackedParameter(0),(GLfloat)getStackedFloat(1));
			break;
		case NFOSMESA_GLMULTITEXCOORD1FVARB:
			nfglMultiTexCoord1fvARB(getStackedParameter(0),(const GLfloat *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1IARB:
			nfglMultiTexCoord1iARB(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLMULTITEXCOORD1IVARB:
			nfglMultiTexCoord1ivARB(getStackedParameter(0),(const GLint *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1SARB:
			nfglMultiTexCoord1sARB(getStackedParameter(0),getStackedParameter(1));
			break;
		case NFOSMESA_GLMULTITEXCOORD1SVARB:
			nfglMultiTexCoord1svARB(getStackedParameter(0),(const GLshort *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2DARB:
			nfglMultiTexCoord2dARB(getStackedParameter(0),Atari2HostDouble(getStackedParameter(1),getStackedParameter(2)),Atari2HostDouble(getStackedParameter(3),getStackedParameter(4)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2DVARB:
			nfglMultiTexCoord2dvARB(getStackedParameter(0),(const GLdouble *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2FARB:
			nfglMultiTexCoord2fARB(getStackedParameter(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2));
			break;
		case NFOSMESA_GLMULTITEXCOORD2FVARB:
			nfglMultiTexCoord2fvARB(getStackedParameter(0),(const GLfloat *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2IARB:
			nfglMultiTexCoord2iARB(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLMULTITEXCOORD2IVARB:
			nfglMultiTexCoord2ivARB(getStackedParameter(0),(const GLint *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2SARB:
			nfglMultiTexCoord2sARB(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2));
			break;
		case NFOSMESA_GLMULTITEXCOORD2SVARB:
			nfglMultiTexCoord2svARB(getStackedParameter(0),(const GLshort *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3DARB:
			nfglMultiTexCoord3dARB(getStackedParameter(0),Atari2HostDouble(getStackedParameter(1),getStackedParameter(2)),Atari2HostDouble(getStackedParameter(3),getStackedParameter(4)),Atari2HostDouble(getStackedParameter(5),getStackedParameter(6)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3DVARB:
			nfglMultiTexCoord3dvARB(getStackedParameter(0),(const GLdouble *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3FARB:
			nfglMultiTexCoord3fARB(getStackedParameter(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2),(GLfloat)getStackedFloat(3));
			break;
		case NFOSMESA_GLMULTITEXCOORD3FVARB:
			nfglMultiTexCoord3fvARB(getStackedParameter(0),(const GLfloat *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3IARB:
			nfglMultiTexCoord3iARB(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLMULTITEXCOORD3IVARB:
			nfglMultiTexCoord3ivARB(getStackedParameter(0),(const GLint *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3SARB:
			nfglMultiTexCoord3sARB(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3));
			break;
		case NFOSMESA_GLMULTITEXCOORD3SVARB:
			nfglMultiTexCoord3svARB(getStackedParameter(0),(const GLshort *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4DARB:
			nfglMultiTexCoord4dARB(getStackedParameter(0),Atari2HostDouble(getStackedParameter(1),getStackedParameter(2)),Atari2HostDouble(getStackedParameter(3),getStackedParameter(4)),Atari2HostDouble(getStackedParameter(5),getStackedParameter(6)),Atari2HostDouble(getStackedParameter(7),getStackedParameter(8)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4DVARB:
			nfglMultiTexCoord4dvARB(getStackedParameter(0),(const GLdouble *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4FARB:
			nfglMultiTexCoord4fARB(getStackedParameter(0),(GLfloat)getStackedFloat(1),(GLfloat)getStackedFloat(2),(GLfloat)getStackedFloat(3),(GLfloat)getStackedFloat(4));
			break;
		case NFOSMESA_GLMULTITEXCOORD4FVARB:
			nfglMultiTexCoord4fvARB(getStackedParameter(0),(const GLfloat *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4IARB:
			nfglMultiTexCoord4iARB(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4));
			break;
		case NFOSMESA_GLMULTITEXCOORD4IVARB:
			nfglMultiTexCoord4ivARB(getStackedParameter(0),(const GLint *)Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4SARB:
			nfglMultiTexCoord4sARB(getStackedParameter(0),getStackedParameter(1),getStackedParameter(2),getStackedParameter(3),getStackedParameter(4));
			break;
		case NFOSMESA_GLMULTITEXCOORD4SVARB:
			nfglMultiTexCoord4svARB(getStackedParameter(0),(const GLshort *)Atari2HostAddr(getStackedParameter(1)));
			break;
*/
		case NFOSMESA_GLENABLETRACEMESA:
			nfglEnableTraceMESA(getStackedParameter(0));
			break;
		case NFOSMESA_GLDISABLETRACEMESA:
			nfglDisableTraceMESA(getStackedParameter(0));
			break;
		case NFOSMESA_GLNEWTRACEMESA:
			nfglNewTraceMESA(getStackedParameter(0),(const GLubyte * )Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLENDTRACEMESA:
			nfglEndTraceMESA();
			break;
		case NFOSMESA_GLTRACEASSERTATTRIBMESA:
			nfglTraceAssertAttribMESA(getStackedParameter(0));
			break;
		case NFOSMESA_GLTRACECOMMENTMESA:
			nfglTraceCommentMESA((const GLubyte *)Atari2HostAddr(getStackedParameter(0)));
			break;
		case NFOSMESA_GLTRACETEXTUREMESA:
			nfglTraceTextureMESA(getStackedParameter(0),(const GLubyte* )Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLTRACELISTMESA:
			nfglTraceListMESA(getStackedParameter(0),(const GLubyte* )Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLTRACEPOINTERMESA:
			nfglTracePointerMESA((GLvoid* )Atari2HostAddr(getStackedParameter(0)),(const GLubyte* )Atari2HostAddr(getStackedParameter(1)));
			break;
		case NFOSMESA_GLTRACEPOINTERRANGEMESA:
			nfglTracePointerRangeMESA((const GLvoid* )Atari2HostAddr(getStackedParameter(0)),(const GLvoid* )Atari2HostAddr(getStackedParameter(1)),(const GLubyte* )Atari2HostAddr(getStackedParameter(2)));
			break;
		case NFOSMESA_GLBLENDEQUATIONSEPARATEATI:
			nfglBlendEquationSeparateATI(getStackedParameter(0),getStackedParameter(1));
			break;
/* Functions generated: 465 */
