/* Generated by dispatch-gen.pl from /usr/local/include/GL/gl.h */

		case NFOSMESA_GLCLEARINDEX:
			glClearIndex(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLCLEARCOLOR:
			glClearColor(getParameter(0),(GLclampf)Atari2HostFloat(getParameter(1),getParameter(2)),(GLclampf)Atari2HostFloat(getParameter(3),getParameter(4)),(GLclampf)Atari2HostFloat(getParameter(5),getParameter(6)),(GLclampf)Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLCLEAR:
			glClear(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLINDEXMASK:
			glIndexMask(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLCOLORMASK:
			glColorMask(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLALPHAFUNC:
			glAlphaFunc(getParameter(0),getParameter(1),(GLclampf)Atari2HostFloat(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLBLENDFUNC:
			glBlendFunc(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLLOGICOP:
			glLogicOp(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLCULLFACE:
			glCullFace(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLFRONTFACE:
			glFrontFace(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLPOINTSIZE:
			glPointSize(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLLINEWIDTH:
			glLineWidth(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLLINESTIPPLE:
			glLineStipple(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLPOLYGONMODE:
			glPolygonMode(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLPOLYGONOFFSET:
			glPolygonOffset(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLPOLYGONSTIPPLE:
			glPolygonStipple(getParameter(0),(const GLubyte *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLGETPOLYGONSTIPPLE:
			glGetPolygonStipple(getParameter(0),(GLubyte *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLEDGEFLAG:
			glEdgeFlag(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLEDGEFLAGV:
			glEdgeFlagv(getParameter(0),(const GLboolean *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLSCISSOR:
			glScissor(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLCLIPPLANE:
			glClipPlane(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLGETCLIPPLANE:
			glGetClipPlane(getParameter(0),getParameter(1),(GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLDRAWBUFFER:
			glDrawBuffer(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLREADBUFFER:
			glReadBuffer(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLENABLE:
			glEnable(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLDISABLE:
			glDisable(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLISENABLED:
			ret = glIsEnabled(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLENABLECLIENTSTATE:
			glEnableClientState(getParameter(0),getParameter(1)); /* 1.1 */
			break;
		case NFOSMESA_GLDISABLECLIENTSTATE:
			glDisableClientState(getParameter(0),getParameter(1)); /* 1.1 */
			break;
		case NFOSMESA_GLGETBOOLEANV:
			glGetBooleanv(getParameter(0),getParameter(1),(GLboolean *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLGETDOUBLEV:
			glGetDoublev(getParameter(0),getParameter(1),(GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLGETFLOATV:
			glGetFloatv(getParameter(0),getParameter(1),(GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLGETINTEGERV:
			glGetIntegerv(getParameter(0),getParameter(1),(GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLPUSHATTRIB:
			glPushAttrib(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLPOPATTRIB:
			glPopAttrib(getParameter(0));
			break;
		case NFOSMESA_GLPUSHCLIENTATTRIB:
			glPushClientAttrib(getParameter(0),getParameter(1)); /* 1.1 */
			break;
		case NFOSMESA_GLPOPCLIENTATTRIB:
			glPopClientAttrib(getParameter(0)); /* 1.1 */
			break;
		case NFOSMESA_GLRENDERMODE:
			ret = glRenderMode(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLGETERROR:
			ret = glGetError(getParameter(0));
			break;
/*
		case NFOSMESA_GLGETSTRING:
			ret = glGetString(getParameter(0),getParameter(1));
			break;
*/
		case NFOSMESA_GLFINISH:
			glFinish(getParameter(0));
			break;
		case NFOSMESA_GLFLUSH:
			glFlush(getParameter(0));
			break;
		case NFOSMESA_GLHINT:
			glHint(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLCLEARDEPTH:
			glClearDepth(getParameter(0),(GLclampd)Atari2HostDouble(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLDEPTHFUNC:
			glDepthFunc(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLDEPTHMASK:
			glDepthMask(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLDEPTHRANGE:
			glDepthRange(getParameter(0),(GLclampd)Atari2HostDouble(getParameter(1),getParameter(2)),(GLclampd)Atari2HostDouble(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLCLEARACCUM:
			glClearAccum(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)),Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLACCUM:
			glAccum(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLMATRIXMODE:
			glMatrixMode(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLORTHO:
			glOrtho(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)),Atari2HostDouble(getParameter(7),getParameter(8)),Atari2HostDouble(getParameter(9),getParameter(10)),Atari2HostDouble(getParameter(11),getParameter(12)));
			break;
		case NFOSMESA_GLFRUSTUM:
			glFrustum(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)),Atari2HostDouble(getParameter(7),getParameter(8)),Atari2HostDouble(getParameter(9),getParameter(10)),Atari2HostDouble(getParameter(11),getParameter(12)));
			break;
		case NFOSMESA_GLVIEWPORT:
			glViewport(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLPUSHMATRIX:
			glPushMatrix(getParameter(0));
			break;
		case NFOSMESA_GLPOPMATRIX:
			glPopMatrix(getParameter(0));
			break;
		case NFOSMESA_GLLOADIDENTITY:
			glLoadIdentity(getParameter(0));
			break;
		case NFOSMESA_GLLOADMATRIXD:
			glLoadMatrixd(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLLOADMATRIXF:
			glLoadMatrixf(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLMULTMATRIXD:
			glMultMatrixd(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLMULTMATRIXF:
			glMultMatrixf(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLROTATED:
			glRotated(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)),Atari2HostDouble(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLROTATEF:
			glRotatef(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)),Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLSCALED:
			glScaled(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLSCALEF:
			glScalef(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLTRANSLATED:
			glTranslated(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLTRANSLATEF:
			glTranslatef(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLISLIST:
			ret = glIsList(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLDELETELISTS:
			glDeleteLists(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLGENLISTS:
			ret = glGenLists(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLNEWLIST:
			glNewList(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLENDLIST:
			glEndList(getParameter(0));
			break;
		case NFOSMESA_GLCALLLIST:
			glCallList(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLCALLLISTS:
			glCallLists(getParameter(0),getParameter(1),getParameter(2),(const GLvoid *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLLISTBASE:
			glListBase(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLBEGIN:
			glBegin(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLEND:
			glEnd(getParameter(0));
			break;
		case NFOSMESA_GLVERTEX2D:
			glVertex2d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLVERTEX2F:
			glVertex2f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLVERTEX2I:
			glVertex2i(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLVERTEX2S:
			glVertex2s(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLVERTEX3D:
			glVertex3d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLVERTEX3F:
			glVertex3f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLVERTEX3I:
			glVertex3i(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLVERTEX3S:
			glVertex3s(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLVERTEX4D:
			glVertex4d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)),Atari2HostDouble(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLVERTEX4F:
			glVertex4f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)),Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLVERTEX4I:
			glVertex4i(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLVERTEX4S:
			glVertex4s(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLVERTEX2DV:
			glVertex2dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX2FV:
			glVertex2fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX2IV:
			glVertex2iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX2SV:
			glVertex2sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX3DV:
			glVertex3dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX3FV:
			glVertex3fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX3IV:
			glVertex3iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX3SV:
			glVertex3sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX4DV:
			glVertex4dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX4FV:
			glVertex4fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX4IV:
			glVertex4iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX4SV:
			glVertex4sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLNORMAL3B:
			glNormal3b(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLNORMAL3D:
			glNormal3d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLNORMAL3F:
			glNormal3f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLNORMAL3I:
			glNormal3i(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLNORMAL3S:
			glNormal3s(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLNORMAL3BV:
			glNormal3bv(getParameter(0),(const GLbyte *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLNORMAL3DV:
			glNormal3dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLNORMAL3FV:
			glNormal3fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLNORMAL3IV:
			glNormal3iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLNORMAL3SV:
			glNormal3sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLINDEXD:
			glIndexd(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLINDEXF:
			glIndexf(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLINDEXI:
			glIndexi(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLINDEXS:
			glIndexs(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLINDEXUB:
			glIndexub(getParameter(0),getParameter(1)); /* 1.1 */
			break;
		case NFOSMESA_GLINDEXDV:
			glIndexdv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLINDEXFV:
			glIndexfv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLINDEXIV:
			glIndexiv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLINDEXSV:
			glIndexsv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLINDEXUBV:
			glIndexubv(getParameter(0),(const GLubyte *)Atari2HostAddr(getParameter(1))); /* 1.1 */
			break;
		case NFOSMESA_GLCOLOR3B:
			glColor3b(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLCOLOR3D:
			glColor3d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLCOLOR3F:
			glColor3f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLCOLOR3I:
			glColor3i(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLCOLOR3S:
			glColor3s(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLCOLOR3UB:
			glColor3ub(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLCOLOR3UI:
			glColor3ui(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLCOLOR3US:
			glColor3us(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLCOLOR4B:
			glColor4b(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLCOLOR4D:
			glColor4d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)),Atari2HostDouble(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLCOLOR4F:
			glColor4f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)),Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLCOLOR4I:
			glColor4i(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLCOLOR4S:
			glColor4s(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLCOLOR4UB:
			glColor4ub(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLCOLOR4UI:
			glColor4ui(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLCOLOR4US:
			glColor4us(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLCOLOR3BV:
			glColor3bv(getParameter(0),(const GLbyte *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR3DV:
			glColor3dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR3FV:
			glColor3fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR3IV:
			glColor3iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR3SV:
			glColor3sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR3UBV:
			glColor3ubv(getParameter(0),(const GLubyte *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR3UIV:
			glColor3uiv(getParameter(0),(const GLuint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR3USV:
			glColor3usv(getParameter(0),(const GLushort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR4BV:
			glColor4bv(getParameter(0),(const GLbyte *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR4DV:
			glColor4dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR4FV:
			glColor4fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR4IV:
			glColor4iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR4SV:
			glColor4sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR4UBV:
			glColor4ubv(getParameter(0),(const GLubyte *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR4UIV:
			glColor4uiv(getParameter(0),(const GLuint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR4USV:
			glColor4usv(getParameter(0),(const GLushort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD1D:
			glTexCoord1d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLTEXCOORD1F:
			glTexCoord1f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLTEXCOORD1I:
			glTexCoord1i(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLTEXCOORD1S:
			glTexCoord1s(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLTEXCOORD2D:
			glTexCoord2d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLTEXCOORD2F:
			glTexCoord2f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLTEXCOORD2I:
			glTexCoord2i(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLTEXCOORD2S:
			glTexCoord2s(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLTEXCOORD3D:
			glTexCoord3d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLTEXCOORD3F:
			glTexCoord3f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLTEXCOORD3I:
			glTexCoord3i(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLTEXCOORD3S:
			glTexCoord3s(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLTEXCOORD4D:
			glTexCoord4d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)),Atari2HostDouble(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLTEXCOORD4F:
			glTexCoord4f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)),Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLTEXCOORD4I:
			glTexCoord4i(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLTEXCOORD4S:
			glTexCoord4s(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLTEXCOORD1DV:
			glTexCoord1dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD1FV:
			glTexCoord1fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD1IV:
			glTexCoord1iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD1SV:
			glTexCoord1sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD2DV:
			glTexCoord2dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD2FV:
			glTexCoord2fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD2IV:
			glTexCoord2iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD2SV:
			glTexCoord2sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD3DV:
			glTexCoord3dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD3FV:
			glTexCoord3fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD3IV:
			glTexCoord3iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD3SV:
			glTexCoord3sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD4DV:
			glTexCoord4dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD4FV:
			glTexCoord4fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD4IV:
			glTexCoord4iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD4SV:
			glTexCoord4sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS2D:
			glRasterPos2d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLRASTERPOS2F:
			glRasterPos2f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLRASTERPOS2I:
			glRasterPos2i(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLRASTERPOS2S:
			glRasterPos2s(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLRASTERPOS3D:
			glRasterPos3d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLRASTERPOS3F:
			glRasterPos3f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLRASTERPOS3I:
			glRasterPos3i(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLRASTERPOS3S:
			glRasterPos3s(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLRASTERPOS4D:
			glRasterPos4d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)),Atari2HostDouble(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLRASTERPOS4F:
			glRasterPos4f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)),Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLRASTERPOS4I:
			glRasterPos4i(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLRASTERPOS4S:
			glRasterPos4s(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLRASTERPOS2DV:
			glRasterPos2dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS2FV:
			glRasterPos2fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS2IV:
			glRasterPos2iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS2SV:
			glRasterPos2sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS3DV:
			glRasterPos3dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS3FV:
			glRasterPos3fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS3IV:
			glRasterPos3iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS3SV:
			glRasterPos3sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS4DV:
			glRasterPos4dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS4FV:
			glRasterPos4fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS4IV:
			glRasterPos4iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS4SV:
			glRasterPos4sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRECTD:
			glRectd(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)),Atari2HostDouble(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLRECTF:
			glRectf(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)),Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLRECTI:
			glRecti(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLRECTS:
			glRects(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLRECTDV:
			glRectdv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLRECTFV:
			glRectfv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLRECTIV:
			glRectiv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLRECTSV:
			glRectsv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLVERTEXPOINTER:
			glVertexPointer(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(const GLvoid *)Atari2HostAddr(getParameter(4)));
			break;
		case NFOSMESA_GLNORMALPOINTER:
			glNormalPointer(getParameter(0),getParameter(1),getParameter(2),(const GLvoid *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLCOLORPOINTER:
			glColorPointer(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(const GLvoid *)Atari2HostAddr(getParameter(4)));
			break;
		case NFOSMESA_GLINDEXPOINTER:
			glIndexPointer(getParameter(0),getParameter(1),getParameter(2),(const GLvoid *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLTEXCOORDPOINTER:
			glTexCoordPointer(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(const GLvoid *)Atari2HostAddr(getParameter(4)));
			break;
		case NFOSMESA_GLEDGEFLAGPOINTER:
			glEdgeFlagPointer(getParameter(0),getParameter(1),(const GLvoid *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLGETPOINTERV:
			glGetPointerv(getParameter(0),getParameter(1),(GLvoid **)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLARRAYELEMENT:
			glArrayElement(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLDRAWARRAYS:
			glDrawArrays(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLDRAWELEMENTS:
			glDrawElements(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(const GLvoid *)Atari2HostAddr(getParameter(4)));
			break;
		case NFOSMESA_GLINTERLEAVEDARRAYS:
			glInterleavedArrays(getParameter(0),getParameter(1),getParameter(2),(const GLvoid *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLSHADEMODEL:
			glShadeModel(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLLIGHTF:
			glLightf(getParameter(0),getParameter(1),getParameter(2),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLLIGHTI:
			glLighti(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLLIGHTFV:
			glLightfv(getParameter(0),getParameter(1),getParameter(2),(const GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLLIGHTIV:
			glLightiv(getParameter(0),getParameter(1),getParameter(2),(const GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETLIGHTFV:
			glGetLightfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETLIGHTIV:
			glGetLightiv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLLIGHTMODELF:
			glLightModelf(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLLIGHTMODELI:
			glLightModeli(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLLIGHTMODELFV:
			glLightModelfv(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLLIGHTMODELIV:
			glLightModeliv(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMATERIALF:
			glMaterialf(getParameter(0),getParameter(1),getParameter(2),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLMATERIALI:
			glMateriali(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLMATERIALFV:
			glMaterialfv(getParameter(0),getParameter(1),getParameter(2),(const GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLMATERIALIV:
			glMaterialiv(getParameter(0),getParameter(1),getParameter(2),(const GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETMATERIALFV:
			glGetMaterialfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETMATERIALIV:
			glGetMaterialiv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLCOLORMATERIAL:
			glColorMaterial(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLPIXELZOOM:
			glPixelZoom(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLPIXELSTOREF:
			glPixelStoref(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLPIXELSTOREI:
			glPixelStorei(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLPIXELTRANSFERF:
			glPixelTransferf(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLPIXELTRANSFERI:
			glPixelTransferi(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLPIXELMAPFV:
			glPixelMapfv(getParameter(0),getParameter(1),getParameter(2),(const GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLPIXELMAPUIV:
			glPixelMapuiv(getParameter(0),getParameter(1),getParameter(2),(const GLuint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLPIXELMAPUSV:
			glPixelMapusv(getParameter(0),getParameter(1),getParameter(2),(const GLushort *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETPIXELMAPFV:
			glGetPixelMapfv(getParameter(0),getParameter(1),(GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLGETPIXELMAPUIV:
			glGetPixelMapuiv(getParameter(0),getParameter(1),(GLuint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLGETPIXELMAPUSV:
			glGetPixelMapusv(getParameter(0),getParameter(1),(GLushort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLBITMAP:
			glBitmap(getParameter(0),getParameter(1),getParameter(2),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)),Atari2HostFloat(getParameter(7),getParameter(8)),Atari2HostFloat(getParameter(9),getParameter(10)),(const GLubyte *)Atari2HostAddr(getParameter(11)));
			break;
		case NFOSMESA_GLREADPIXELS:
			glReadPixels(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),(GLvoid *)Atari2HostAddr(getParameter(7)));
			break;
		case NFOSMESA_GLDRAWPIXELS:
			glDrawPixels(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),(const GLvoid *)Atari2HostAddr(getParameter(5)));
			break;
		case NFOSMESA_GLCOPYPIXELS:
			glCopyPixels(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLSTENCILFUNC:
			glStencilFunc(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLSTENCILMASK:
			glStencilMask(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLSTENCILOP:
			glStencilOp(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLCLEARSTENCIL:
			glClearStencil(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLTEXGEND:
			glTexGend(getParameter(0),getParameter(1),getParameter(2),Atari2HostDouble(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLTEXGENF:
			glTexGenf(getParameter(0),getParameter(1),getParameter(2),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLTEXGENI:
			glTexGeni(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLTEXGENDV:
			glTexGendv(getParameter(0),getParameter(1),getParameter(2),(const GLdouble *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLTEXGENFV:
			glTexGenfv(getParameter(0),getParameter(1),getParameter(2),(const GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLTEXGENIV:
			glTexGeniv(getParameter(0),getParameter(1),getParameter(2),(const GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETTEXGENDV:
			glGetTexGendv(getParameter(0),getParameter(1),getParameter(2),(GLdouble *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETTEXGENFV:
			glGetTexGenfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETTEXGENIV:
			glGetTexGeniv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLTEXENVF:
			glTexEnvf(getParameter(0),getParameter(1),getParameter(2),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLTEXENVI:
			glTexEnvi(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLTEXENVFV:
			glTexEnvfv(getParameter(0),getParameter(1),getParameter(2),(const GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLTEXENVIV:
			glTexEnviv(getParameter(0),getParameter(1),getParameter(2),(const GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETTEXENVFV:
			glGetTexEnvfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETTEXENVIV:
			glGetTexEnviv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLTEXPARAMETERF:
			glTexParameterf(getParameter(0),getParameter(1),getParameter(2),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLTEXPARAMETERI:
			glTexParameteri(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLTEXPARAMETERFV:
			glTexParameterfv(getParameter(0),getParameter(1),getParameter(2),(const GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLTEXPARAMETERIV:
			glTexParameteriv(getParameter(0),getParameter(1),getParameter(2),(const GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETTEXPARAMETERFV:
			glGetTexParameterfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETTEXPARAMETERIV:
			glGetTexParameteriv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETTEXLEVELPARAMETERFV:
			glGetTexLevelParameterfv(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(GLfloat *)Atari2HostAddr(getParameter(4)));
			break;
		case NFOSMESA_GLGETTEXLEVELPARAMETERIV:
			glGetTexLevelParameteriv(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(GLint *)Atari2HostAddr(getParameter(4)));
			break;
		case NFOSMESA_GLTEXIMAGE1D:
			glTexImage1D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),(const GLvoid *)Atari2HostAddr(getParameter(8)));
			break;
		case NFOSMESA_GLTEXIMAGE2D:
			glTexImage2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8),(const GLvoid *)Atari2HostAddr(getParameter(9)));
			break;
		case NFOSMESA_GLGETTEXIMAGE:
			glGetTexImage(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),(GLvoid *)Atari2HostAddr(getParameter(5)));
			break;
		case NFOSMESA_GLGENTEXTURES:
			glGenTextures(getParameter(0),getParameter(1),(GLuint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLDELETETEXTURES:
			glDeleteTextures(getParameter(0),getParameter(1),(const GLuint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLBINDTEXTURE:
			glBindTexture(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLPRIORITIZETEXTURES:
			glPrioritizeTextures(getParameter(0),getParameter(1),(const GLuint *)Atari2HostAddr(getParameter(2)),(const GLclampf *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLARETEXTURESRESIDENT:
			ret = glAreTexturesResident(getParameter(0),getParameter(1),(const GLuint *)Atari2HostAddr(getParameter(2)),(GLboolean *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLISTEXTURE:
			ret = glIsTexture(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLTEXSUBIMAGE1D:
			glTexSubImage1D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),(const GLvoid *)Atari2HostAddr(getParameter(7)));
			break;
		case NFOSMESA_GLTEXSUBIMAGE2D:
			glTexSubImage2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8),(const GLvoid *)Atari2HostAddr(getParameter(9)));
			break;
		case NFOSMESA_GLCOPYTEXIMAGE1D:
			glCopyTexImage1D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7));
			break;
		case NFOSMESA_GLCOPYTEXIMAGE2D:
			glCopyTexImage2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8));
			break;
		case NFOSMESA_GLCOPYTEXSUBIMAGE1D:
			glCopyTexSubImage1D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6));
			break;
		case NFOSMESA_GLCOPYTEXSUBIMAGE2D:
			glCopyTexSubImage2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8));
			break;
		case NFOSMESA_GLMAP1D:
			glMap1d(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)),getParameter(6),getParameter(7),(const GLdouble *)Atari2HostAddr(getParameter(8)));
			break;
		case NFOSMESA_GLMAP1F:
			glMap1f(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)),getParameter(6),getParameter(7),(const GLfloat *)Atari2HostAddr(getParameter(8)));
			break;
		case NFOSMESA_GLMAP2D:
			glMap2d(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)),getParameter(6),getParameter(7),Atari2HostDouble(getParameter(8),getParameter(9)),Atari2HostDouble(getParameter(10),getParameter(11)),getParameter(12),getParameter(13),(const GLdouble *)Atari2HostAddr(getParameter(14)));
			break;
		case NFOSMESA_GLMAP2F:
			glMap2f(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)),getParameter(6),getParameter(7),Atari2HostFloat(getParameter(8),getParameter(9)),Atari2HostFloat(getParameter(10),getParameter(11)),getParameter(12),getParameter(13),(const GLfloat *)Atari2HostAddr(getParameter(14)));
			break;
		case NFOSMESA_GLGETMAPDV:
			glGetMapdv(getParameter(0),getParameter(1),getParameter(2),(GLdouble *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETMAPFV:
			glGetMapfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETMAPIV:
			glGetMapiv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLEVALCOORD1D:
			glEvalCoord1d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLEVALCOORD1F:
			glEvalCoord1f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLEVALCOORD1DV:
			glEvalCoord1dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLEVALCOORD1FV:
			glEvalCoord1fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLEVALCOORD2D:
			glEvalCoord2d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLEVALCOORD2F:
			glEvalCoord2f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLEVALCOORD2DV:
			glEvalCoord2dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLEVALCOORD2FV:
			glEvalCoord2fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLMAPGRID1D:
			glMapGrid1d(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)));
			break;
		case NFOSMESA_GLMAPGRID1F:
			glMapGrid1f(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)));
			break;
		case NFOSMESA_GLMAPGRID2D:
			glMapGrid2d(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)),getParameter(6),Atari2HostDouble(getParameter(7),getParameter(8)),Atari2HostDouble(getParameter(9),getParameter(10)));
			break;
		case NFOSMESA_GLMAPGRID2F:
			glMapGrid2f(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)),getParameter(6),Atari2HostFloat(getParameter(7),getParameter(8)),Atari2HostFloat(getParameter(9),getParameter(10)));
			break;
		case NFOSMESA_GLEVALPOINT1:
			glEvalPoint1(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLEVALPOINT2:
			glEvalPoint2(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLEVALMESH1:
			glEvalMesh1(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLEVALMESH2:
			glEvalMesh2(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLFOGF:
			glFogf(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLFOGI:
			glFogi(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLFOGFV:
			glFogfv(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLFOGIV:
			glFogiv(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLFEEDBACKBUFFER:
			glFeedbackBuffer(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLPASSTHROUGH:
			glPassThrough(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLSELECTBUFFER:
			glSelectBuffer(getParameter(0),getParameter(1),(GLuint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLINITNAMES:
			glInitNames(getParameter(0));
			break;
		case NFOSMESA_GLLOADNAME:
			glLoadName(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLPUSHNAME:
			glPushName(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLPOPNAME:
			glPopName(getParameter(0));
			break;
/*
		case NFOSMESA_GLDRAWRANGEELEMENTS:
			glDrawRangeElements(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),(const GLvoid *)Atari2HostAddr(getParameter(6)));
			break;
		case NFOSMESA_GLTEXIMAGE3D:
			glTexImage3D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8),getParameter(9),(const GLvoid *)Atari2HostAddr(getParameter(10)));
			break;
		case NFOSMESA_GLTEXSUBIMAGE3D:
			glTexSubImage3D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8),getParameter(9),getParameter(10),(const GLvoid *)Atari2HostAddr(getParameter(11)));
			break;
		case NFOSMESA_GLCOPYTEXSUBIMAGE3D:
			glCopyTexSubImage3D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8),getParameter(9));
			break;
		case NFOSMESA_GLCOLORTABLE:
			glColorTable(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),(const GLvoid *)Atari2HostAddr(getParameter(6)));
			break;
		case NFOSMESA_GLCOLORSUBTABLE:
			glColorSubTable(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),(const GLvoid *)Atari2HostAddr(getParameter(6)));
			break;
		case NFOSMESA_GLCOLORTABLEPARAMETERIV:
			glColorTableParameteriv(getParameter(0),getParameter(1),getParameter(2),(const GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLCOLORTABLEPARAMETERFV:
			glColorTableParameterfv(getParameter(0),getParameter(1),getParameter(2),(const GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLCOPYCOLORSUBTABLE:
			glCopyColorSubTable(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLCOPYCOLORTABLE:
			glCopyColorTable(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLGETCOLORTABLE:
			glGetColorTable(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(GLvoid *)Atari2HostAddr(getParameter(4)));
			break;
		case NFOSMESA_GLGETCOLORTABLEPARAMETERFV:
			glGetColorTableParameterfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETCOLORTABLEPARAMETERIV:
			glGetColorTableParameteriv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLBLENDEQUATION:
			glBlendEquation(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLBLENDCOLOR:
			glBlendColor(getParameter(0),(GLclampf)Atari2HostFloat(getParameter(1),getParameter(2)),(GLclampf)Atari2HostFloat(getParameter(3),getParameter(4)),(GLclampf)Atari2HostFloat(getParameter(5),getParameter(6)),(GLclampf)Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLHISTOGRAM:
			glHistogram(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLRESETHISTOGRAM:
			glResetHistogram(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLGETHISTOGRAM:
			glGetHistogram(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),(GLvoid *)Atari2HostAddr(getParameter(5)));
			break;
		case NFOSMESA_GLGETHISTOGRAMPARAMETERFV:
			glGetHistogramParameterfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETHISTOGRAMPARAMETERIV:
			glGetHistogramParameteriv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLMINMAX:
			glMinmax(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLRESETMINMAX:
			glResetMinmax(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLGETMINMAX:
			glGetMinmax(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),(GLvoid *)Atari2HostAddr(getParameter(5)));
			break;
		case NFOSMESA_GLGETMINMAXPARAMETERFV:
			glGetMinmaxParameterfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETMINMAXPARAMETERIV:
			glGetMinmaxParameteriv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLCONVOLUTIONFILTER1D:
			glConvolutionFilter1D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),(const GLvoid *)Atari2HostAddr(getParameter(6)));
			break;
		case NFOSMESA_GLCONVOLUTIONFILTER2D:
			glConvolutionFilter2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),(const GLvoid *)Atari2HostAddr(getParameter(7)));
			break;
		case NFOSMESA_GLCONVOLUTIONPARAMETERF:
			glConvolutionParameterf(getParameter(0),getParameter(1),getParameter(2),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLCONVOLUTIONPARAMETERFV:
			glConvolutionParameterfv(getParameter(0),getParameter(1),getParameter(2),(const GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLCONVOLUTIONPARAMETERI:
			glConvolutionParameteri(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLCONVOLUTIONPARAMETERIV:
			glConvolutionParameteriv(getParameter(0),getParameter(1),getParameter(2),(const GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLCOPYCONVOLUTIONFILTER1D:
			glCopyConvolutionFilter1D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLCOPYCONVOLUTIONFILTER2D:
			glCopyConvolutionFilter2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6));
			break;
		case NFOSMESA_GLGETCONVOLUTIONFILTER:
			glGetConvolutionFilter(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(GLvoid *)Atari2HostAddr(getParameter(4)));
			break;
		case NFOSMESA_GLGETCONVOLUTIONPARAMETERFV:
			glGetConvolutionParameterfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETCONVOLUTIONPARAMETERIV:
			glGetConvolutionParameteriv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLSEPARABLEFILTER2D:
			glSeparableFilter2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),(const GLvoid *)Atari2HostAddr(getParameter(7)),(const GLvoid *)Atari2HostAddr(getParameter(8)));
			break;
		case NFOSMESA_GLGETSEPARABLEFILTER:
			glGetSeparableFilter(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(GLvoid *)Atari2HostAddr(getParameter(4)),(GLvoid *)Atari2HostAddr(getParameter(5)),(GLvoid *)Atari2HostAddr(getParameter(6)));
			break;
		case NFOSMESA_GLACTIVETEXTURE:
			glActiveTexture(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLCLIENTACTIVETEXTURE:
			glClientActiveTexture(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXIMAGE1D:
			glCompressedTexImage1D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),(const GLvoid *)Atari2HostAddr(getParameter(7)));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXIMAGE2D:
			glCompressedTexImage2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),(const GLvoid *)Atari2HostAddr(getParameter(8)));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXIMAGE3D:
			glCompressedTexImage3D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8),(const GLvoid *)Atari2HostAddr(getParameter(9)));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXSUBIMAGE1D:
			glCompressedTexSubImage1D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),(const GLvoid *)Atari2HostAddr(getParameter(7)));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXSUBIMAGE2D:
			glCompressedTexSubImage2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8),(const GLvoid *)Atari2HostAddr(getParameter(9)));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXSUBIMAGE3D:
			glCompressedTexSubImage3D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8),getParameter(9),getParameter(10),(const GLvoid *)Atari2HostAddr(getParameter(11)));
			break;
		case NFOSMESA_GLGETCOMPRESSEDTEXIMAGE:
			glGetCompressedTexImage(getParameter(0),getParameter(1),getParameter(2),(GLvoid *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1D:
			glMultiTexCoord1d(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1DV:
			glMultiTexCoord1dv(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1F:
			glMultiTexCoord1f(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1FV:
			glMultiTexCoord1fv(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1I:
			glMultiTexCoord1i(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLMULTITEXCOORD1IV:
			glMultiTexCoord1iv(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1S:
			glMultiTexCoord1s(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLMULTITEXCOORD1SV:
			glMultiTexCoord1sv(getParameter(0),getParameter(1),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2D:
			glMultiTexCoord2d(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2DV:
			glMultiTexCoord2dv(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2F:
			glMultiTexCoord2f(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2FV:
			glMultiTexCoord2fv(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2I:
			glMultiTexCoord2i(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLMULTITEXCOORD2IV:
			glMultiTexCoord2iv(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2S:
			glMultiTexCoord2s(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLMULTITEXCOORD2SV:
			glMultiTexCoord2sv(getParameter(0),getParameter(1),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3D:
			glMultiTexCoord3d(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)),Atari2HostDouble(getParameter(6),getParameter(7)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3DV:
			glMultiTexCoord3dv(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3F:
			glMultiTexCoord3f(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)),Atari2HostFloat(getParameter(6),getParameter(7)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3FV:
			glMultiTexCoord3fv(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3I:
			glMultiTexCoord3i(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLMULTITEXCOORD3IV:
			glMultiTexCoord3iv(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3S:
			glMultiTexCoord3s(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLMULTITEXCOORD3SV:
			glMultiTexCoord3sv(getParameter(0),getParameter(1),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4D:
			glMultiTexCoord4d(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)),Atari2HostDouble(getParameter(6),getParameter(7)),Atari2HostDouble(getParameter(8),getParameter(9)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4DV:
			glMultiTexCoord4dv(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4F:
			glMultiTexCoord4f(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)),Atari2HostFloat(getParameter(6),getParameter(7)),Atari2HostFloat(getParameter(8),getParameter(9)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4FV:
			glMultiTexCoord4fv(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4I:
			glMultiTexCoord4i(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLMULTITEXCOORD4IV:
			glMultiTexCoord4iv(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4S:
			glMultiTexCoord4s(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLMULTITEXCOORD4SV:
			glMultiTexCoord4sv(getParameter(0),getParameter(1),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLLOADTRANSPOSEMATRIXD:
			glLoadTransposeMatrixd(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLLOADTRANSPOSEMATRIXF:
			glLoadTransposeMatrixf(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLMULTTRANSPOSEMATRIXD:
			glMultTransposeMatrixd(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLMULTTRANSPOSEMATRIXF:
			glMultTransposeMatrixf(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLSAMPLECOVERAGE:
			glSampleCoverage(getParameter(0),(GLclampf)Atari2HostFloat(getParameter(1),getParameter(2)),getParameter(3));
			break;
		case NFOSMESA_GLACTIVETEXTUREARB:
			glActiveTextureARB(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLCLIENTACTIVETEXTUREARB:
			glClientActiveTextureARB(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLMULTITEXCOORD1DARB:
			glMultiTexCoord1dARB(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1DVARB:
			glMultiTexCoord1dvARB(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1FARB:
			glMultiTexCoord1fARB(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1FVARB:
			glMultiTexCoord1fvARB(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1IARB:
			glMultiTexCoord1iARB(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLMULTITEXCOORD1IVARB:
			glMultiTexCoord1ivARB(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1SARB:
			glMultiTexCoord1sARB(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLMULTITEXCOORD1SVARB:
			glMultiTexCoord1svARB(getParameter(0),getParameter(1),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2DARB:
			glMultiTexCoord2dARB(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2DVARB:
			glMultiTexCoord2dvARB(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2FARB:
			glMultiTexCoord2fARB(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2FVARB:
			glMultiTexCoord2fvARB(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2IARB:
			glMultiTexCoord2iARB(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLMULTITEXCOORD2IVARB:
			glMultiTexCoord2ivARB(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2SARB:
			glMultiTexCoord2sARB(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLMULTITEXCOORD2SVARB:
			glMultiTexCoord2svARB(getParameter(0),getParameter(1),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3DARB:
			glMultiTexCoord3dARB(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)),Atari2HostDouble(getParameter(6),getParameter(7)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3DVARB:
			glMultiTexCoord3dvARB(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3FARB:
			glMultiTexCoord3fARB(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)),Atari2HostFloat(getParameter(6),getParameter(7)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3FVARB:
			glMultiTexCoord3fvARB(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3IARB:
			glMultiTexCoord3iARB(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLMULTITEXCOORD3IVARB:
			glMultiTexCoord3ivARB(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3SARB:
			glMultiTexCoord3sARB(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLMULTITEXCOORD3SVARB:
			glMultiTexCoord3svARB(getParameter(0),getParameter(1),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4DARB:
			glMultiTexCoord4dARB(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)),Atari2HostDouble(getParameter(6),getParameter(7)),Atari2HostDouble(getParameter(8),getParameter(9)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4DVARB:
			glMultiTexCoord4dvARB(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4FARB:
			glMultiTexCoord4fARB(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)),Atari2HostFloat(getParameter(6),getParameter(7)),Atari2HostFloat(getParameter(8),getParameter(9)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4FVARB:
			glMultiTexCoord4fvARB(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4IARB:
			glMultiTexCoord4iARB(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLMULTITEXCOORD4IVARB:
			glMultiTexCoord4ivARB(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4SARB:
			glMultiTexCoord4sARB(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLMULTITEXCOORD4SVARB:
			glMultiTexCoord4svARB(getParameter(0),getParameter(1),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
*/
		case NFOSMESA_GLENABLETRACEMESA:
			glEnableTraceMESA(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLDISABLETRACEMESA:
			glDisableTraceMESA(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLNEWTRACEMESA:
			glNewTraceMESA(getParameter(0),getParameter(1),(const GLubyte * )Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLENDTRACEMESA:
			glEndTraceMESA(getParameter(0));
			break;
		case NFOSMESA_GLTRACEASSERTATTRIBMESA:
			glTraceAssertAttribMESA(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLTRACECOMMENTMESA:
			glTraceCommentMESA(getParameter(0),(const GLubyte *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTRACETEXTUREMESA:
			glTraceTextureMESA(getParameter(0),getParameter(1),(const GLubyte* )Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLTRACELISTMESA:
			glTraceListMESA(getParameter(0),getParameter(1),(const GLubyte* )Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLTRACEPOINTERMESA:
			glTracePointerMESA(getParameter(0),(GLvoid* )Atari2HostAddr(getParameter(1)),(const GLubyte* )Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLTRACEPOINTERRANGEMESA:
			glTracePointerRangeMESA(getParameter(0),(const GLvoid* )Atari2HostAddr(getParameter(1)),(const GLvoid* )Atari2HostAddr(getParameter(2)),(const GLubyte* )Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLBLENDEQUATIONSEPARATEATI:
			glBlendEquationSeparateATI(getParameter(0),getParameter(1),getParameter(2));
			break;
/* Functions generated: 465 */
