/* Generated by dispatch-gen.pl from /usr/local/include/GL/gl.h */

		case NFOSMESA_GLCLEARINDEX:
			nfglClearIndex(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLCLEARCOLOR:
			nfglClearColor(getParameter(0),(GLclampf)Atari2HostFloat(getParameter(1),getParameter(2)),(GLclampf)Atari2HostFloat(getParameter(3),getParameter(4)),(GLclampf)Atari2HostFloat(getParameter(5),getParameter(6)),(GLclampf)Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLCLEAR:
			nfglClear(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLINDEXMASK:
			nfglIndexMask(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLCOLORMASK:
			nfglColorMask(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLALPHAFUNC:
			nfglAlphaFunc(getParameter(0),getParameter(1),(GLclampf)Atari2HostFloat(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLBLENDFUNC:
			nfglBlendFunc(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLLOGICOP:
			nfglLogicOp(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLCULLFACE:
			nfglCullFace(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLFRONTFACE:
			nfglFrontFace(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLPOINTSIZE:
			nfglPointSize(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLLINEWIDTH:
			nfglLineWidth(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLLINESTIPPLE:
			nfglLineStipple(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLPOLYGONMODE:
			nfglPolygonMode(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLPOLYGONOFFSET:
			nfglPolygonOffset(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLPOLYGONSTIPPLE:
			nfglPolygonStipple(getParameter(0),(const GLubyte *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLGETPOLYGONSTIPPLE:
			nfglGetPolygonStipple(getParameter(0),(GLubyte *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLEDGEFLAG:
			nfglEdgeFlag(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLEDGEFLAGV:
			nfglEdgeFlagv(getParameter(0),(const GLboolean *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLSCISSOR:
			nfglScissor(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLCLIPPLANE:
			nfglClipPlane(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLGETCLIPPLANE:
			nfglGetClipPlane(getParameter(0),getParameter(1),(GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLDRAWBUFFER:
			nfglDrawBuffer(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLREADBUFFER:
			nfglReadBuffer(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLENABLE:
			nfglEnable(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLDISABLE:
			nfglDisable(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLISENABLED:
			ret = nfglIsEnabled(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLENABLECLIENTSTATE:
			nfglEnableClientState(getParameter(0),getParameter(1)); /* 1.1 */
			break;
		case NFOSMESA_GLDISABLECLIENTSTATE:
			nfglDisableClientState(getParameter(0),getParameter(1)); /* 1.1 */
			break;
		case NFOSMESA_GLGETBOOLEANV:
			nfglGetBooleanv(getParameter(0),getParameter(1),(GLboolean *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLGETDOUBLEV:
			nfglGetDoublev(getParameter(0),getParameter(1),(GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLGETFLOATV:
			nfglGetFloatv(getParameter(0),getParameter(1),(GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLGETINTEGERV:
			nfglGetIntegerv(getParameter(0),getParameter(1),(GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLPUSHATTRIB:
			nfglPushAttrib(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLPOPATTRIB:
			nfglPopAttrib(getParameter(0));
			break;
		case NFOSMESA_GLPUSHCLIENTATTRIB:
			nfglPushClientAttrib(getParameter(0),getParameter(1)); /* 1.1 */
			break;
		case NFOSMESA_GLPOPCLIENTATTRIB:
			nfglPopClientAttrib(getParameter(0)); /* 1.1 */
			break;
		case NFOSMESA_GLRENDERMODE:
			ret = nfglRenderMode(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLGETERROR:
			ret = nfglGetError(getParameter(0));
			break;
/*
		case NFOSMESA_GLGETSTRING:
			ret = nfglGetString(getParameter(0),getParameter(1));
			break;
*/
		case NFOSMESA_GLFINISH:
			nfglFinish(getParameter(0));
			break;
		case NFOSMESA_GLFLUSH:
			nfglFlush(getParameter(0));
			break;
		case NFOSMESA_GLHINT:
			nfglHint(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLCLEARDEPTH:
			nfglClearDepth(getParameter(0),(GLclampd)Atari2HostDouble(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLDEPTHFUNC:
			nfglDepthFunc(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLDEPTHMASK:
			nfglDepthMask(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLDEPTHRANGE:
			nfglDepthRange(getParameter(0),(GLclampd)Atari2HostDouble(getParameter(1),getParameter(2)),(GLclampd)Atari2HostDouble(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLCLEARACCUM:
			nfglClearAccum(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)),Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLACCUM:
			nfglAccum(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLMATRIXMODE:
			nfglMatrixMode(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLORTHO:
			nfglOrtho(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)),Atari2HostDouble(getParameter(7),getParameter(8)),Atari2HostDouble(getParameter(9),getParameter(10)),Atari2HostDouble(getParameter(11),getParameter(12)));
			break;
		case NFOSMESA_GLFRUSTUM:
			nfglFrustum(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)),Atari2HostDouble(getParameter(7),getParameter(8)),Atari2HostDouble(getParameter(9),getParameter(10)),Atari2HostDouble(getParameter(11),getParameter(12)));
			break;
		case NFOSMESA_GLVIEWPORT:
			nfglViewport(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLPUSHMATRIX:
			nfglPushMatrix(getParameter(0));
			break;
		case NFOSMESA_GLPOPMATRIX:
			nfglPopMatrix(getParameter(0));
			break;
		case NFOSMESA_GLLOADIDENTITY:
			nfglLoadIdentity(getParameter(0));
			break;
		case NFOSMESA_GLLOADMATRIXD:
			nfglLoadMatrixd(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLLOADMATRIXF:
			nfglLoadMatrixf(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLMULTMATRIXD:
			nfglMultMatrixd(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLMULTMATRIXF:
			nfglMultMatrixf(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLROTATED:
			nfglRotated(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)),Atari2HostDouble(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLROTATEF:
			nfglRotatef(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)),Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLSCALED:
			nfglScaled(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLSCALEF:
			nfglScalef(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLTRANSLATED:
			nfglTranslated(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLTRANSLATEF:
			nfglTranslatef(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLISLIST:
			ret = nfglIsList(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLDELETELISTS:
			nfglDeleteLists(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLGENLISTS:
			ret = nfglGenLists(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLNEWLIST:
			nfglNewList(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLENDLIST:
			nfglEndList(getParameter(0));
			break;
		case NFOSMESA_GLCALLLIST:
			nfglCallList(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLCALLLISTS:
			nfglCallLists(getParameter(0),getParameter(1),getParameter(2),(const GLvoid *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLLISTBASE:
			nfglListBase(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLBEGIN:
			nfglBegin(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLEND:
			nfglEnd(getParameter(0));
			break;
		case NFOSMESA_GLVERTEX2D:
			nfglVertex2d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLVERTEX2F:
			nfglVertex2f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLVERTEX2I:
			nfglVertex2i(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLVERTEX2S:
			nfglVertex2s(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLVERTEX3D:
			nfglVertex3d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLVERTEX3F:
			nfglVertex3f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLVERTEX3I:
			nfglVertex3i(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLVERTEX3S:
			nfglVertex3s(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLVERTEX4D:
			nfglVertex4d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)),Atari2HostDouble(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLVERTEX4F:
			nfglVertex4f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)),Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLVERTEX4I:
			nfglVertex4i(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLVERTEX4S:
			nfglVertex4s(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLVERTEX2DV:
			nfglVertex2dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX2FV:
			nfglVertex2fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX2IV:
			nfglVertex2iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX2SV:
			nfglVertex2sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX3DV:
			nfglVertex3dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX3FV:
			nfglVertex3fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX3IV:
			nfglVertex3iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX3SV:
			nfglVertex3sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX4DV:
			nfglVertex4dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX4FV:
			nfglVertex4fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX4IV:
			nfglVertex4iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLVERTEX4SV:
			nfglVertex4sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLNORMAL3B:
			nfglNormal3b(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLNORMAL3D:
			nfglNormal3d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLNORMAL3F:
			nfglNormal3f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLNORMAL3I:
			nfglNormal3i(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLNORMAL3S:
			nfglNormal3s(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLNORMAL3BV:
			nfglNormal3bv(getParameter(0),(const GLbyte *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLNORMAL3DV:
			nfglNormal3dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLNORMAL3FV:
			nfglNormal3fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLNORMAL3IV:
			nfglNormal3iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLNORMAL3SV:
			nfglNormal3sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLINDEXD:
			nfglIndexd(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLINDEXF:
			nfglIndexf(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLINDEXI:
			nfglIndexi(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLINDEXS:
			nfglIndexs(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLINDEXUB:
			nfglIndexub(getParameter(0),getParameter(1)); /* 1.1 */
			break;
		case NFOSMESA_GLINDEXDV:
			nfglIndexdv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLINDEXFV:
			nfglIndexfv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLINDEXIV:
			nfglIndexiv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLINDEXSV:
			nfglIndexsv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLINDEXUBV:
			nfglIndexubv(getParameter(0),(const GLubyte *)Atari2HostAddr(getParameter(1))); /* 1.1 */
			break;
		case NFOSMESA_GLCOLOR3B:
			nfglColor3b(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLCOLOR3D:
			nfglColor3d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLCOLOR3F:
			nfglColor3f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLCOLOR3I:
			nfglColor3i(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLCOLOR3S:
			nfglColor3s(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLCOLOR3UB:
			nfglColor3ub(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLCOLOR3UI:
			nfglColor3ui(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLCOLOR3US:
			nfglColor3us(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLCOLOR4B:
			nfglColor4b(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLCOLOR4D:
			nfglColor4d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)),Atari2HostDouble(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLCOLOR4F:
			nfglColor4f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)),Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLCOLOR4I:
			nfglColor4i(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLCOLOR4S:
			nfglColor4s(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLCOLOR4UB:
			nfglColor4ub(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLCOLOR4UI:
			nfglColor4ui(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLCOLOR4US:
			nfglColor4us(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLCOLOR3BV:
			nfglColor3bv(getParameter(0),(const GLbyte *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR3DV:
			nfglColor3dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR3FV:
			nfglColor3fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR3IV:
			nfglColor3iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR3SV:
			nfglColor3sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR3UBV:
			nfglColor3ubv(getParameter(0),(const GLubyte *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR3UIV:
			nfglColor3uiv(getParameter(0),(const GLuint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR3USV:
			nfglColor3usv(getParameter(0),(const GLushort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR4BV:
			nfglColor4bv(getParameter(0),(const GLbyte *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR4DV:
			nfglColor4dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR4FV:
			nfglColor4fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR4IV:
			nfglColor4iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR4SV:
			nfglColor4sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR4UBV:
			nfglColor4ubv(getParameter(0),(const GLubyte *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR4UIV:
			nfglColor4uiv(getParameter(0),(const GLuint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLCOLOR4USV:
			nfglColor4usv(getParameter(0),(const GLushort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD1D:
			nfglTexCoord1d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLTEXCOORD1F:
			nfglTexCoord1f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLTEXCOORD1I:
			nfglTexCoord1i(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLTEXCOORD1S:
			nfglTexCoord1s(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLTEXCOORD2D:
			nfglTexCoord2d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLTEXCOORD2F:
			nfglTexCoord2f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLTEXCOORD2I:
			nfglTexCoord2i(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLTEXCOORD2S:
			nfglTexCoord2s(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLTEXCOORD3D:
			nfglTexCoord3d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLTEXCOORD3F:
			nfglTexCoord3f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLTEXCOORD3I:
			nfglTexCoord3i(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLTEXCOORD3S:
			nfglTexCoord3s(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLTEXCOORD4D:
			nfglTexCoord4d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)),Atari2HostDouble(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLTEXCOORD4F:
			nfglTexCoord4f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)),Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLTEXCOORD4I:
			nfglTexCoord4i(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLTEXCOORD4S:
			nfglTexCoord4s(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLTEXCOORD1DV:
			nfglTexCoord1dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD1FV:
			nfglTexCoord1fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD1IV:
			nfglTexCoord1iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD1SV:
			nfglTexCoord1sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD2DV:
			nfglTexCoord2dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD2FV:
			nfglTexCoord2fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD2IV:
			nfglTexCoord2iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD2SV:
			nfglTexCoord2sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD3DV:
			nfglTexCoord3dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD3FV:
			nfglTexCoord3fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD3IV:
			nfglTexCoord3iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD3SV:
			nfglTexCoord3sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD4DV:
			nfglTexCoord4dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD4FV:
			nfglTexCoord4fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD4IV:
			nfglTexCoord4iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTEXCOORD4SV:
			nfglTexCoord4sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS2D:
			nfglRasterPos2d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLRASTERPOS2F:
			nfglRasterPos2f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLRASTERPOS2I:
			nfglRasterPos2i(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLRASTERPOS2S:
			nfglRasterPos2s(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLRASTERPOS3D:
			nfglRasterPos3d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLRASTERPOS3F:
			nfglRasterPos3f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)));
			break;
		case NFOSMESA_GLRASTERPOS3I:
			nfglRasterPos3i(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLRASTERPOS3S:
			nfglRasterPos3s(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLRASTERPOS4D:
			nfglRasterPos4d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)),Atari2HostDouble(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLRASTERPOS4F:
			nfglRasterPos4f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)),Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLRASTERPOS4I:
			nfglRasterPos4i(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLRASTERPOS4S:
			nfglRasterPos4s(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLRASTERPOS2DV:
			nfglRasterPos2dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS2FV:
			nfglRasterPos2fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS2IV:
			nfglRasterPos2iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS2SV:
			nfglRasterPos2sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS3DV:
			nfglRasterPos3dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS3FV:
			nfglRasterPos3fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS3IV:
			nfglRasterPos3iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS3SV:
			nfglRasterPos3sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS4DV:
			nfglRasterPos4dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS4FV:
			nfglRasterPos4fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS4IV:
			nfglRasterPos4iv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRASTERPOS4SV:
			nfglRasterPos4sv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLRECTD:
			nfglRectd(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)),Atari2HostDouble(getParameter(5),getParameter(6)),Atari2HostDouble(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLRECTF:
			nfglRectf(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)),Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLRECTI:
			nfglRecti(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLRECTS:
			nfglRects(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLRECTDV:
			nfglRectdv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLRECTFV:
			nfglRectfv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLRECTIV:
			nfglRectiv(getParameter(0),(const GLint *)Atari2HostAddr(getParameter(1)),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLRECTSV:
			nfglRectsv(getParameter(0),(const GLshort *)Atari2HostAddr(getParameter(1)),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLVERTEXPOINTER:
			nfglVertexPointer(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(const GLvoid *)Atari2HostAddr(getParameter(4)));
			break;
		case NFOSMESA_GLNORMALPOINTER:
			nfglNormalPointer(getParameter(0),getParameter(1),getParameter(2),(const GLvoid *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLCOLORPOINTER:
			nfglColorPointer(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(const GLvoid *)Atari2HostAddr(getParameter(4)));
			break;
		case NFOSMESA_GLINDEXPOINTER:
			nfglIndexPointer(getParameter(0),getParameter(1),getParameter(2),(const GLvoid *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLTEXCOORDPOINTER:
			nfglTexCoordPointer(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(const GLvoid *)Atari2HostAddr(getParameter(4)));
			break;
		case NFOSMESA_GLEDGEFLAGPOINTER:
			nfglEdgeFlagPointer(getParameter(0),getParameter(1),(const GLvoid *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLGETPOINTERV:
			nfglGetPointerv(getParameter(0),getParameter(1),(GLvoid **)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLARRAYELEMENT:
			nfglArrayElement(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLDRAWARRAYS:
			nfglDrawArrays(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLDRAWELEMENTS:
			nfglDrawElements(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(const GLvoid *)Atari2HostAddr(getParameter(4)));
			break;
		case NFOSMESA_GLINTERLEAVEDARRAYS:
			nfglInterleavedArrays(getParameter(0),getParameter(1),getParameter(2),(const GLvoid *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLSHADEMODEL:
			nfglShadeModel(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLLIGHTF:
			nfglLightf(getParameter(0),getParameter(1),getParameter(2),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLLIGHTI:
			nfglLighti(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLLIGHTFV:
			nfglLightfv(getParameter(0),getParameter(1),getParameter(2),(const GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLLIGHTIV:
			nfglLightiv(getParameter(0),getParameter(1),getParameter(2),(const GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETLIGHTFV:
			nfglGetLightfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETLIGHTIV:
			nfglGetLightiv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLLIGHTMODELF:
			nfglLightModelf(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLLIGHTMODELI:
			nfglLightModeli(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLLIGHTMODELFV:
			nfglLightModelfv(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLLIGHTMODELIV:
			nfglLightModeliv(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMATERIALF:
			nfglMaterialf(getParameter(0),getParameter(1),getParameter(2),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLMATERIALI:
			nfglMateriali(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLMATERIALFV:
			nfglMaterialfv(getParameter(0),getParameter(1),getParameter(2),(const GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLMATERIALIV:
			nfglMaterialiv(getParameter(0),getParameter(1),getParameter(2),(const GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETMATERIALFV:
			nfglGetMaterialfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETMATERIALIV:
			nfglGetMaterialiv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLCOLORMATERIAL:
			nfglColorMaterial(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLPIXELZOOM:
			nfglPixelZoom(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLPIXELSTOREF:
			nfglPixelStoref(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLPIXELSTOREI:
			nfglPixelStorei(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLPIXELTRANSFERF:
			nfglPixelTransferf(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLPIXELTRANSFERI:
			nfglPixelTransferi(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLPIXELMAPFV:
			nfglPixelMapfv(getParameter(0),getParameter(1),getParameter(2),(const GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLPIXELMAPUIV:
			nfglPixelMapuiv(getParameter(0),getParameter(1),getParameter(2),(const GLuint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLPIXELMAPUSV:
			nfglPixelMapusv(getParameter(0),getParameter(1),getParameter(2),(const GLushort *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETPIXELMAPFV:
			nfglGetPixelMapfv(getParameter(0),getParameter(1),(GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLGETPIXELMAPUIV:
			nfglGetPixelMapuiv(getParameter(0),getParameter(1),(GLuint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLGETPIXELMAPUSV:
			nfglGetPixelMapusv(getParameter(0),getParameter(1),(GLushort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLBITMAP:
			nfglBitmap(getParameter(0),getParameter(1),getParameter(2),Atari2HostFloat(getParameter(3),getParameter(4)),Atari2HostFloat(getParameter(5),getParameter(6)),Atari2HostFloat(getParameter(7),getParameter(8)),Atari2HostFloat(getParameter(9),getParameter(10)),(const GLubyte *)Atari2HostAddr(getParameter(11)));
			break;
		case NFOSMESA_GLREADPIXELS:
			nfglReadPixels(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),(GLvoid *)Atari2HostAddr(getParameter(7)));
			break;
		case NFOSMESA_GLDRAWPIXELS:
			nfglDrawPixels(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),(const GLvoid *)Atari2HostAddr(getParameter(5)));
			break;
		case NFOSMESA_GLCOPYPIXELS:
			nfglCopyPixels(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLSTENCILFUNC:
			nfglStencilFunc(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLSTENCILMASK:
			nfglStencilMask(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLSTENCILOP:
			nfglStencilOp(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLCLEARSTENCIL:
			nfglClearStencil(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLTEXGEND:
			nfglTexGend(getParameter(0),getParameter(1),getParameter(2),Atari2HostDouble(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLTEXGENF:
			nfglTexGenf(getParameter(0),getParameter(1),getParameter(2),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLTEXGENI:
			nfglTexGeni(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLTEXGENDV:
			nfglTexGendv(getParameter(0),getParameter(1),getParameter(2),(const GLdouble *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLTEXGENFV:
			nfglTexGenfv(getParameter(0),getParameter(1),getParameter(2),(const GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLTEXGENIV:
			nfglTexGeniv(getParameter(0),getParameter(1),getParameter(2),(const GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETTEXGENDV:
			nfglGetTexGendv(getParameter(0),getParameter(1),getParameter(2),(GLdouble *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETTEXGENFV:
			nfglGetTexGenfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETTEXGENIV:
			nfglGetTexGeniv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLTEXENVF:
			nfglTexEnvf(getParameter(0),getParameter(1),getParameter(2),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLTEXENVI:
			nfglTexEnvi(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLTEXENVFV:
			nfglTexEnvfv(getParameter(0),getParameter(1),getParameter(2),(const GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLTEXENVIV:
			nfglTexEnviv(getParameter(0),getParameter(1),getParameter(2),(const GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETTEXENVFV:
			nfglGetTexEnvfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETTEXENVIV:
			nfglGetTexEnviv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLTEXPARAMETERF:
			nfglTexParameterf(getParameter(0),getParameter(1),getParameter(2),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLTEXPARAMETERI:
			nfglTexParameteri(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLTEXPARAMETERFV:
			nfglTexParameterfv(getParameter(0),getParameter(1),getParameter(2),(const GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLTEXPARAMETERIV:
			nfglTexParameteriv(getParameter(0),getParameter(1),getParameter(2),(const GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETTEXPARAMETERFV:
			nfglGetTexParameterfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETTEXPARAMETERIV:
			nfglGetTexParameteriv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETTEXLEVELPARAMETERFV:
			nfglGetTexLevelParameterfv(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(GLfloat *)Atari2HostAddr(getParameter(4)));
			break;
		case NFOSMESA_GLGETTEXLEVELPARAMETERIV:
			nfglGetTexLevelParameteriv(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(GLint *)Atari2HostAddr(getParameter(4)));
			break;
		case NFOSMESA_GLTEXIMAGE1D:
			nfglTexImage1D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),(const GLvoid *)Atari2HostAddr(getParameter(8)));
			break;
		case NFOSMESA_GLTEXIMAGE2D:
			nfglTexImage2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8),(const GLvoid *)Atari2HostAddr(getParameter(9)));
			break;
		case NFOSMESA_GLGETTEXIMAGE:
			nfglGetTexImage(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),(GLvoid *)Atari2HostAddr(getParameter(5)));
			break;
		case NFOSMESA_GLGENTEXTURES:
			nfglGenTextures(getParameter(0),getParameter(1),(GLuint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLDELETETEXTURES:
			nfglDeleteTextures(getParameter(0),getParameter(1),(const GLuint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLBINDTEXTURE:
			nfglBindTexture(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLPRIORITIZETEXTURES:
			nfglPrioritizeTextures(getParameter(0),getParameter(1),(const GLuint *)Atari2HostAddr(getParameter(2)),(const GLclampf *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLARETEXTURESRESIDENT:
			ret = nfglAreTexturesResident(getParameter(0),getParameter(1),(const GLuint *)Atari2HostAddr(getParameter(2)),(GLboolean *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLISTEXTURE:
			ret = nfglIsTexture(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLTEXSUBIMAGE1D:
			nfglTexSubImage1D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),(const GLvoid *)Atari2HostAddr(getParameter(7)));
			break;
		case NFOSMESA_GLTEXSUBIMAGE2D:
			nfglTexSubImage2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8),(const GLvoid *)Atari2HostAddr(getParameter(9)));
			break;
		case NFOSMESA_GLCOPYTEXIMAGE1D:
			nfglCopyTexImage1D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7));
			break;
		case NFOSMESA_GLCOPYTEXIMAGE2D:
			nfglCopyTexImage2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8));
			break;
		case NFOSMESA_GLCOPYTEXSUBIMAGE1D:
			nfglCopyTexSubImage1D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6));
			break;
		case NFOSMESA_GLCOPYTEXSUBIMAGE2D:
			nfglCopyTexSubImage2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8));
			break;
		case NFOSMESA_GLMAP1D:
			nfglMap1d(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)),getParameter(6),getParameter(7),(const GLdouble *)Atari2HostAddr(getParameter(8)));
			break;
		case NFOSMESA_GLMAP1F:
			nfglMap1f(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)),getParameter(6),getParameter(7),(const GLfloat *)Atari2HostAddr(getParameter(8)));
			break;
		case NFOSMESA_GLMAP2D:
			nfglMap2d(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)),getParameter(6),getParameter(7),Atari2HostDouble(getParameter(8),getParameter(9)),Atari2HostDouble(getParameter(10),getParameter(11)),getParameter(12),getParameter(13),(const GLdouble *)Atari2HostAddr(getParameter(14)));
			break;
		case NFOSMESA_GLMAP2F:
			nfglMap2f(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)),getParameter(6),getParameter(7),Atari2HostFloat(getParameter(8),getParameter(9)),Atari2HostFloat(getParameter(10),getParameter(11)),getParameter(12),getParameter(13),(const GLfloat *)Atari2HostAddr(getParameter(14)));
			break;
		case NFOSMESA_GLGETMAPDV:
			nfglGetMapdv(getParameter(0),getParameter(1),getParameter(2),(GLdouble *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETMAPFV:
			nfglGetMapfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETMAPIV:
			nfglGetMapiv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLEVALCOORD1D:
			nfglEvalCoord1d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLEVALCOORD1F:
			nfglEvalCoord1f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLEVALCOORD1DV:
			nfglEvalCoord1dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLEVALCOORD1FV:
			nfglEvalCoord1fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLEVALCOORD2D:
			nfglEvalCoord2d(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)),Atari2HostDouble(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLEVALCOORD2F:
			nfglEvalCoord2f(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLEVALCOORD2DV:
			nfglEvalCoord2dv(getParameter(0),(const GLdouble *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLEVALCOORD2FV:
			nfglEvalCoord2fv(getParameter(0),(const GLfloat *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLMAPGRID1D:
			nfglMapGrid1d(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)));
			break;
		case NFOSMESA_GLMAPGRID1F:
			nfglMapGrid1f(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)));
			break;
		case NFOSMESA_GLMAPGRID2D:
			nfglMapGrid2d(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)),getParameter(6),Atari2HostDouble(getParameter(7),getParameter(8)),Atari2HostDouble(getParameter(9),getParameter(10)));
			break;
		case NFOSMESA_GLMAPGRID2F:
			nfglMapGrid2f(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)),getParameter(6),Atari2HostFloat(getParameter(7),getParameter(8)),Atari2HostFloat(getParameter(9),getParameter(10)));
			break;
		case NFOSMESA_GLEVALPOINT1:
			nfglEvalPoint1(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLEVALPOINT2:
			nfglEvalPoint2(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLEVALMESH1:
			nfglEvalMesh1(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLEVALMESH2:
			nfglEvalMesh2(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLFOGF:
			nfglFogf(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLFOGI:
			nfglFogi(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLFOGFV:
			nfglFogfv(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLFOGIV:
			nfglFogiv(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLFEEDBACKBUFFER:
			nfglFeedbackBuffer(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLPASSTHROUGH:
			nfglPassThrough(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLSELECTBUFFER:
			nfglSelectBuffer(getParameter(0),getParameter(1),(GLuint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLINITNAMES:
			nfglInitNames(getParameter(0));
			break;
		case NFOSMESA_GLLOADNAME:
			nfglLoadName(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLPUSHNAME:
			nfglPushName(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLPOPNAME:
			nfglPopName(getParameter(0));
			break;
/*
		case NFOSMESA_GLDRAWRANGEELEMENTS:
			nfglDrawRangeElements(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),(const GLvoid *)Atari2HostAddr(getParameter(6)));
			break;
		case NFOSMESA_GLTEXIMAGE3D:
			nfglTexImage3D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8),getParameter(9),(const GLvoid *)Atari2HostAddr(getParameter(10)));
			break;
		case NFOSMESA_GLTEXSUBIMAGE3D:
			nfglTexSubImage3D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8),getParameter(9),getParameter(10),(const GLvoid *)Atari2HostAddr(getParameter(11)));
			break;
		case NFOSMESA_GLCOPYTEXSUBIMAGE3D:
			nfglCopyTexSubImage3D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8),getParameter(9));
			break;
		case NFOSMESA_GLCOLORTABLE:
			nfglColorTable(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),(const GLvoid *)Atari2HostAddr(getParameter(6)));
			break;
		case NFOSMESA_GLCOLORSUBTABLE:
			nfglColorSubTable(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),(const GLvoid *)Atari2HostAddr(getParameter(6)));
			break;
		case NFOSMESA_GLCOLORTABLEPARAMETERIV:
			nfglColorTableParameteriv(getParameter(0),getParameter(1),getParameter(2),(const GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLCOLORTABLEPARAMETERFV:
			nfglColorTableParameterfv(getParameter(0),getParameter(1),getParameter(2),(const GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLCOPYCOLORSUBTABLE:
			nfglCopyColorSubTable(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLCOPYCOLORTABLE:
			nfglCopyColorTable(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLGETCOLORTABLE:
			nfglGetColorTable(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(GLvoid *)Atari2HostAddr(getParameter(4)));
			break;
		case NFOSMESA_GLGETCOLORTABLEPARAMETERFV:
			nfglGetColorTableParameterfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETCOLORTABLEPARAMETERIV:
			nfglGetColorTableParameteriv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLBLENDEQUATION:
			nfglBlendEquation(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLBLENDCOLOR:
			nfglBlendColor(getParameter(0),(GLclampf)Atari2HostFloat(getParameter(1),getParameter(2)),(GLclampf)Atari2HostFloat(getParameter(3),getParameter(4)),(GLclampf)Atari2HostFloat(getParameter(5),getParameter(6)),(GLclampf)Atari2HostFloat(getParameter(7),getParameter(8)));
			break;
		case NFOSMESA_GLHISTOGRAM:
			nfglHistogram(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLRESETHISTOGRAM:
			nfglResetHistogram(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLGETHISTOGRAM:
			nfglGetHistogram(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),(GLvoid *)Atari2HostAddr(getParameter(5)));
			break;
		case NFOSMESA_GLGETHISTOGRAMPARAMETERFV:
			nfglGetHistogramParameterfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETHISTOGRAMPARAMETERIV:
			nfglGetHistogramParameteriv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLMINMAX:
			nfglMinmax(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLRESETMINMAX:
			nfglResetMinmax(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLGETMINMAX:
			nfglGetMinmax(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),(GLvoid *)Atari2HostAddr(getParameter(5)));
			break;
		case NFOSMESA_GLGETMINMAXPARAMETERFV:
			nfglGetMinmaxParameterfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETMINMAXPARAMETERIV:
			nfglGetMinmaxParameteriv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLCONVOLUTIONFILTER1D:
			nfglConvolutionFilter1D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),(const GLvoid *)Atari2HostAddr(getParameter(6)));
			break;
		case NFOSMESA_GLCONVOLUTIONFILTER2D:
			nfglConvolutionFilter2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),(const GLvoid *)Atari2HostAddr(getParameter(7)));
			break;
		case NFOSMESA_GLCONVOLUTIONPARAMETERF:
			nfglConvolutionParameterf(getParameter(0),getParameter(1),getParameter(2),Atari2HostFloat(getParameter(3),getParameter(4)));
			break;
		case NFOSMESA_GLCONVOLUTIONPARAMETERFV:
			nfglConvolutionParameterfv(getParameter(0),getParameter(1),getParameter(2),(const GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLCONVOLUTIONPARAMETERI:
			nfglConvolutionParameteri(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLCONVOLUTIONPARAMETERIV:
			nfglConvolutionParameteriv(getParameter(0),getParameter(1),getParameter(2),(const GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLCOPYCONVOLUTIONFILTER1D:
			nfglCopyConvolutionFilter1D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLCOPYCONVOLUTIONFILTER2D:
			nfglCopyConvolutionFilter2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6));
			break;
		case NFOSMESA_GLGETCONVOLUTIONFILTER:
			nfglGetConvolutionFilter(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(GLvoid *)Atari2HostAddr(getParameter(4)));
			break;
		case NFOSMESA_GLGETCONVOLUTIONPARAMETERFV:
			nfglGetConvolutionParameterfv(getParameter(0),getParameter(1),getParameter(2),(GLfloat *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLGETCONVOLUTIONPARAMETERIV:
			nfglGetConvolutionParameteriv(getParameter(0),getParameter(1),getParameter(2),(GLint *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLSEPARABLEFILTER2D:
			nfglSeparableFilter2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),(const GLvoid *)Atari2HostAddr(getParameter(7)),(const GLvoid *)Atari2HostAddr(getParameter(8)));
			break;
		case NFOSMESA_GLGETSEPARABLEFILTER:
			nfglGetSeparableFilter(getParameter(0),getParameter(1),getParameter(2),getParameter(3),(GLvoid *)Atari2HostAddr(getParameter(4)),(GLvoid *)Atari2HostAddr(getParameter(5)),(GLvoid *)Atari2HostAddr(getParameter(6)));
			break;
		case NFOSMESA_GLACTIVETEXTURE:
			nfglActiveTexture(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLCLIENTACTIVETEXTURE:
			nfglClientActiveTexture(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXIMAGE1D:
			nfglCompressedTexImage1D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),(const GLvoid *)Atari2HostAddr(getParameter(7)));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXIMAGE2D:
			nfglCompressedTexImage2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),(const GLvoid *)Atari2HostAddr(getParameter(8)));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXIMAGE3D:
			nfglCompressedTexImage3D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8),(const GLvoid *)Atari2HostAddr(getParameter(9)));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXSUBIMAGE1D:
			nfglCompressedTexSubImage1D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),(const GLvoid *)Atari2HostAddr(getParameter(7)));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXSUBIMAGE2D:
			nfglCompressedTexSubImage2D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8),(const GLvoid *)Atari2HostAddr(getParameter(9)));
			break;
		case NFOSMESA_GLCOMPRESSEDTEXSUBIMAGE3D:
			nfglCompressedTexSubImage3D(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5),getParameter(6),getParameter(7),getParameter(8),getParameter(9),getParameter(10),(const GLvoid *)Atari2HostAddr(getParameter(11)));
			break;
		case NFOSMESA_GLGETCOMPRESSEDTEXIMAGE:
			nfglGetCompressedTexImage(getParameter(0),getParameter(1),getParameter(2),(GLvoid *)Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1D:
			nfglMultiTexCoord1d(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1DV:
			nfglMultiTexCoord1dv(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1F:
			nfglMultiTexCoord1f(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1FV:
			nfglMultiTexCoord1fv(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1I:
			nfglMultiTexCoord1i(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLMULTITEXCOORD1IV:
			nfglMultiTexCoord1iv(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1S:
			nfglMultiTexCoord1s(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLMULTITEXCOORD1SV:
			nfglMultiTexCoord1sv(getParameter(0),getParameter(1),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2D:
			nfglMultiTexCoord2d(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2DV:
			nfglMultiTexCoord2dv(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2F:
			nfglMultiTexCoord2f(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2FV:
			nfglMultiTexCoord2fv(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2I:
			nfglMultiTexCoord2i(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLMULTITEXCOORD2IV:
			nfglMultiTexCoord2iv(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2S:
			nfglMultiTexCoord2s(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLMULTITEXCOORD2SV:
			nfglMultiTexCoord2sv(getParameter(0),getParameter(1),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3D:
			nfglMultiTexCoord3d(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)),Atari2HostDouble(getParameter(6),getParameter(7)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3DV:
			nfglMultiTexCoord3dv(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3F:
			nfglMultiTexCoord3f(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)),Atari2HostFloat(getParameter(6),getParameter(7)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3FV:
			nfglMultiTexCoord3fv(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3I:
			nfglMultiTexCoord3i(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLMULTITEXCOORD3IV:
			nfglMultiTexCoord3iv(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3S:
			nfglMultiTexCoord3s(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLMULTITEXCOORD3SV:
			nfglMultiTexCoord3sv(getParameter(0),getParameter(1),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4D:
			nfglMultiTexCoord4d(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)),Atari2HostDouble(getParameter(6),getParameter(7)),Atari2HostDouble(getParameter(8),getParameter(9)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4DV:
			nfglMultiTexCoord4dv(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4F:
			nfglMultiTexCoord4f(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)),Atari2HostFloat(getParameter(6),getParameter(7)),Atari2HostFloat(getParameter(8),getParameter(9)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4FV:
			nfglMultiTexCoord4fv(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4I:
			nfglMultiTexCoord4i(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLMULTITEXCOORD4IV:
			nfglMultiTexCoord4iv(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4S:
			nfglMultiTexCoord4s(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLMULTITEXCOORD4SV:
			nfglMultiTexCoord4sv(getParameter(0),getParameter(1),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLLOADTRANSPOSEMATRIXD:
			nfglLoadTransposeMatrixd(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLLOADTRANSPOSEMATRIXF:
			nfglLoadTransposeMatrixf(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLMULTTRANSPOSEMATRIXD:
			nfglMultTransposeMatrixd(getParameter(0),Atari2HostDouble(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLMULTTRANSPOSEMATRIXF:
			nfglMultTransposeMatrixf(getParameter(0),Atari2HostFloat(getParameter(1),getParameter(2)));
			break;
		case NFOSMESA_GLSAMPLECOVERAGE:
			nfglSampleCoverage(getParameter(0),(GLclampf)Atari2HostFloat(getParameter(1),getParameter(2)),getParameter(3));
			break;
		case NFOSMESA_GLACTIVETEXTUREARB:
			nfglActiveTextureARB(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLCLIENTACTIVETEXTUREARB:
			nfglClientActiveTextureARB(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLMULTITEXCOORD1DARB:
			nfglMultiTexCoord1dARB(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1DVARB:
			nfglMultiTexCoord1dvARB(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1FARB:
			nfglMultiTexCoord1fARB(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1FVARB:
			nfglMultiTexCoord1fvARB(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1IARB:
			nfglMultiTexCoord1iARB(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLMULTITEXCOORD1IVARB:
			nfglMultiTexCoord1ivARB(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD1SARB:
			nfglMultiTexCoord1sARB(getParameter(0),getParameter(1),getParameter(2));
			break;
		case NFOSMESA_GLMULTITEXCOORD1SVARB:
			nfglMultiTexCoord1svARB(getParameter(0),getParameter(1),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2DARB:
			nfglMultiTexCoord2dARB(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2DVARB:
			nfglMultiTexCoord2dvARB(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2FARB:
			nfglMultiTexCoord2fARB(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2FVARB:
			nfglMultiTexCoord2fvARB(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2IARB:
			nfglMultiTexCoord2iARB(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLMULTITEXCOORD2IVARB:
			nfglMultiTexCoord2ivARB(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD2SARB:
			nfglMultiTexCoord2sARB(getParameter(0),getParameter(1),getParameter(2),getParameter(3));
			break;
		case NFOSMESA_GLMULTITEXCOORD2SVARB:
			nfglMultiTexCoord2svARB(getParameter(0),getParameter(1),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3DARB:
			nfglMultiTexCoord3dARB(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)),Atari2HostDouble(getParameter(6),getParameter(7)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3DVARB:
			nfglMultiTexCoord3dvARB(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3FARB:
			nfglMultiTexCoord3fARB(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)),Atari2HostFloat(getParameter(6),getParameter(7)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3FVARB:
			nfglMultiTexCoord3fvARB(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3IARB:
			nfglMultiTexCoord3iARB(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLMULTITEXCOORD3IVARB:
			nfglMultiTexCoord3ivARB(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD3SARB:
			nfglMultiTexCoord3sARB(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4));
			break;
		case NFOSMESA_GLMULTITEXCOORD3SVARB:
			nfglMultiTexCoord3svARB(getParameter(0),getParameter(1),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4DARB:
			nfglMultiTexCoord4dARB(getParameter(0),getParameter(1),Atari2HostDouble(getParameter(2),getParameter(3)),Atari2HostDouble(getParameter(4),getParameter(5)),Atari2HostDouble(getParameter(6),getParameter(7)),Atari2HostDouble(getParameter(8),getParameter(9)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4DVARB:
			nfglMultiTexCoord4dvARB(getParameter(0),getParameter(1),(const GLdouble *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4FARB:
			nfglMultiTexCoord4fARB(getParameter(0),getParameter(1),Atari2HostFloat(getParameter(2),getParameter(3)),Atari2HostFloat(getParameter(4),getParameter(5)),Atari2HostFloat(getParameter(6),getParameter(7)),Atari2HostFloat(getParameter(8),getParameter(9)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4FVARB:
			nfglMultiTexCoord4fvARB(getParameter(0),getParameter(1),(const GLfloat *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4IARB:
			nfglMultiTexCoord4iARB(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLMULTITEXCOORD4IVARB:
			nfglMultiTexCoord4ivARB(getParameter(0),getParameter(1),(const GLint *)Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLMULTITEXCOORD4SARB:
			nfglMultiTexCoord4sARB(getParameter(0),getParameter(1),getParameter(2),getParameter(3),getParameter(4),getParameter(5));
			break;
		case NFOSMESA_GLMULTITEXCOORD4SVARB:
			nfglMultiTexCoord4svARB(getParameter(0),getParameter(1),(const GLshort *)Atari2HostAddr(getParameter(2)));
			break;
*/
		case NFOSMESA_GLENABLETRACEMESA:
			nfglEnableTraceMESA(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLDISABLETRACEMESA:
			nfglDisableTraceMESA(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLNEWTRACEMESA:
			nfglNewTraceMESA(getParameter(0),getParameter(1),(const GLubyte * )Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLENDTRACEMESA:
			nfglEndTraceMESA(getParameter(0));
			break;
		case NFOSMESA_GLTRACEASSERTATTRIBMESA:
			nfglTraceAssertAttribMESA(getParameter(0),getParameter(1));
			break;
		case NFOSMESA_GLTRACECOMMENTMESA:
			nfglTraceCommentMESA(getParameter(0),(const GLubyte *)Atari2HostAddr(getParameter(1)));
			break;
		case NFOSMESA_GLTRACETEXTUREMESA:
			nfglTraceTextureMESA(getParameter(0),getParameter(1),(const GLubyte* )Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLTRACELISTMESA:
			nfglTraceListMESA(getParameter(0),getParameter(1),(const GLubyte* )Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLTRACEPOINTERMESA:
			nfglTracePointerMESA(getParameter(0),(GLvoid* )Atari2HostAddr(getParameter(1)),(const GLubyte* )Atari2HostAddr(getParameter(2)));
			break;
		case NFOSMESA_GLTRACEPOINTERRANGEMESA:
			nfglTracePointerRangeMESA(getParameter(0),(const GLvoid* )Atari2HostAddr(getParameter(1)),(const GLvoid* )Atari2HostAddr(getParameter(2)),(const GLubyte* )Atari2HostAddr(getParameter(3)));
			break;
		case NFOSMESA_GLBLENDEQUATIONSEPARATEATI:
			nfglBlendEquationSeparateATI(getParameter(0),getParameter(1),getParameter(2));
			break;

/* Functions generated: 465 */
