/* Generated by ptr-gen.pl from ../../mesa-ldg-1.0/src/link-osmesa.h */

OSMesaContext (*OSMesaCreateContext)( GLenum format, OSMesaContext sharelist );
OSMesaContext (*OSMesaCreateContextExt)( GLenum format, GLint depthBits, GLint stencilBits, GLint accumBits, OSMesaContext sharelist);
void (*OSMesaDestroyContext)( OSMesaContext ctx );
GLboolean (*OSMesaMakeCurrent)( OSMesaContext ctx, void *buffer, GLenum type, GLsizei width, GLsizei height );
OSMesaContext (*OSMesaGetCurrentContext)( void );
void (*OSMesaPixelStore)( GLint pname, GLint value );
void (*OSMesaGetIntegerv)( GLint pname, GLint *value );
GLboolean (*OSMesaGetDepthBuffer)( OSMesaContext c, GLint *width, GLint *height, GLint *bytesPerValue, void **buffer );
GLboolean (*OSMesaGetColorBuffer)( OSMesaContext c, GLint *width, GLint *height, GLint *format, void **buffer );
void * (*OSMesaGetProcAddress)( const char *funcName );
/* Functions generated : 10 */
