/* Generated by unload-gen.pl from pointers-gl.h */

	fn.glClearIndex =
		( void (*)(GLfloat c ))
		NULL;
	fn.glClearColor =
		( void (*)(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha ))
		NULL;
	fn.glClear =
		( void (*)(GLbitfield mask ))
		NULL;
	fn.glIndexMask =
		( void (*)(GLuint mask ))
		NULL;
	fn.glColorMask =
		( void (*)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha ))
		NULL;
	fn.glAlphaFunc =
		( void (*)(GLenum func, GLclampf ref ))
		NULL;
	fn.glBlendFunc =
		( void (*)(GLenum sfactor, GLenum dfactor ))
		NULL;
	fn.glLogicOp =
		( void (*)(GLenum opcode ))
		NULL;
	fn.glCullFace =
		( void (*)(GLenum mode ))
		NULL;
	fn.glFrontFace =
		( void (*)(GLenum mode ))
		NULL;
	fn.glPointSize =
		( void (*)(GLfloat size ))
		NULL;
	fn.glLineWidth =
		( void (*)(GLfloat width ))
		NULL;
	fn.glLineStipple =
		( void (*)(GLint factor, GLushort pattern ))
		NULL;
	fn.glPolygonMode =
		( void (*)(GLenum face, GLenum mode ))
		NULL;
	fn.glPolygonOffset =
		( void (*)(GLfloat factor, GLfloat units ))
		NULL;
	fn.glPolygonStipple =
		( void (*)(const GLubyte *mask ))
		NULL;
	fn.glGetPolygonStipple =
		( void (*)(GLubyte *mask ))
		NULL;
	fn.glEdgeFlag =
		( void (*)(GLboolean flag ))
		NULL;
	fn.glEdgeFlagv =
		( void (*)(const GLboolean *flag ))
		NULL;
	fn.glScissor =
		( void (*)(GLint x, GLint y, GLsizei width, GLsizei height))
		NULL;
	fn.glClipPlane =
		( void (*)(GLenum plane, const GLdouble *equation ))
		NULL;
	fn.glGetClipPlane =
		( void (*)(GLenum plane, GLdouble *equation ))
		NULL;
	fn.glDrawBuffer =
		( void (*)(GLenum mode ))
		NULL;
	fn.glReadBuffer =
		( void (*)(GLenum mode ))
		NULL;
	fn.glEnable =
		( void (*)(GLenum cap ))
		NULL;
	fn.glDisable =
		( void (*)(GLenum cap ))
		NULL;
	fn.glIsEnabled =
		( GLboolean (*)(GLenum cap ))
		NULL;
	fn.glEnableClientState =
		( void (*)(GLenum cap ))
		NULL;
	fn.glDisableClientState =
		( void (*)(GLenum cap ))
		NULL;
	fn.glGetBooleanv =
		( void (*)(GLenum pname, GLboolean *params ))
		NULL;
	fn.glGetDoublev =
		( void (*)(GLenum pname, GLdouble *params ))
		NULL;
	fn.glGetFloatv =
		( void (*)(GLenum pname, GLfloat *params ))
		NULL;
	fn.glGetIntegerv =
		( void (*)(GLenum pname, GLint *params ))
		NULL;
	fn.glPushAttrib =
		( void (*)(GLbitfield mask ))
		NULL;
	fn.glPopAttrib =
		( void (*)(void))
		NULL;
	fn.glPushClientAttrib =
		( void (*)(GLbitfield mask ))
		NULL;
	fn.glPopClientAttrib =
		( void (*)(void))
		NULL;
	fn.glRenderMode =
		( GLint (*)(GLenum mode ))
		NULL;
	fn.glGetError =
		( GLenum (*)(void))
		NULL;
	fn.glGetString =
		( const GLubyte* (*)(GLenum name ))
		NULL;
	fn.glFinish =
		( void (*)(void))
		NULL;
	fn.glFlush =
		( void (*)(void))
		NULL;
	fn.glHint =
		( void (*)(GLenum target, GLenum mode ))
		NULL;
	fn.glClearDepth =
		( void (*)(GLclampd depth ))
		NULL;
	fn.glDepthFunc =
		( void (*)(GLenum func ))
		NULL;
	fn.glDepthMask =
		( void (*)(GLboolean flag ))
		NULL;
	fn.glDepthRange =
		( void (*)(GLclampd near_val, GLclampd far_val ))
		NULL;
	fn.glClearAccum =
		( void (*)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha ))
		NULL;
	fn.glAccum =
		( void (*)(GLenum op, GLfloat value ))
		NULL;
	fn.glMatrixMode =
		( void (*)(GLenum mode ))
		NULL;
	fn.glOrtho =
		( void (*)(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val ))
		NULL;
	fn.glFrustum =
		( void (*)(GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val ))
		NULL;
	fn.glViewport =
		( void (*)(GLint x, GLint y, GLsizei width, GLsizei height ))
		NULL;
	fn.glPushMatrix =
		( void (*)(void))
		NULL;
	fn.glPopMatrix =
		( void (*)(void))
		NULL;
	fn.glLoadIdentity =
		( void (*)(void))
		NULL;
	fn.glLoadMatrixd =
		( void (*)(const GLdouble *m ))
		NULL;
	fn.glLoadMatrixf =
		( void (*)(const GLfloat *m ))
		NULL;
	fn.glMultMatrixd =
		( void (*)(const GLdouble *m ))
		NULL;
	fn.glMultMatrixf =
		( void (*)(const GLfloat *m ))
		NULL;
	fn.glRotated =
		( void (*)(GLdouble an, GLdouble x, GLdouble y, GLdouble z ))
		NULL;
	fn.glRotatef =
		( void (*)(GLfloat an, GLfloat x, GLfloat y, GLfloat z ))
		NULL;
	fn.glScaled =
		( void (*)(GLdouble x, GLdouble y, GLdouble z ))
		NULL;
	fn.glScalef =
		( void (*)(GLfloat x, GLfloat y, GLfloat z ))
		NULL;
	fn.glTranslated =
		( void (*)(GLdouble x, GLdouble y, GLdouble z ))
		NULL;
	fn.glTranslatef =
		( void (*)(GLfloat x, GLfloat y, GLfloat z ))
		NULL;
	fn.glIsList =
		( GLboolean (*)(GLuint list ))
		NULL;
	fn.glDeleteLists =
		( void (*)(GLuint list, GLsizei range ))
		NULL;
	fn.glGenLists =
		( GLuint (*)(GLsizei range ))
		NULL;
	fn.glNewList =
		( void (*)(GLuint list, GLenum mode ))
		NULL;
	fn.glEndList =
		( void (*)(void))
		NULL;
	fn.glCallList =
		( void (*)(GLuint list ))
		NULL;
	fn.glCallLists =
		( void (*)(GLsizei n, GLenum type, const GLvoid *lists ))
		NULL;
	fn.glListBase =
		( void (*)(GLuint base ))
		NULL;
	fn.glBegin =
		( void (*)(GLenum mode ))
		NULL;
	fn.glEnd =
		( void (*)(void))
		NULL;
	fn.glVertex2d =
		( void (*)(GLdouble x, GLdouble y ))
		NULL;
	fn.glVertex2f =
		( void (*)(GLfloat x, GLfloat y ))
		NULL;
	fn.glVertex2i =
		( void (*)(GLint x, GLint y ))
		NULL;
	fn.glVertex2s =
		( void (*)(GLshort x, GLshort y ))
		NULL;
	fn.glVertex3d =
		( void (*)(GLdouble x, GLdouble y, GLdouble z ))
		NULL;
	fn.glVertex3f =
		( void (*)(GLfloat x, GLfloat y, GLfloat z ))
		NULL;
	fn.glVertex3i =
		( void (*)(GLint x, GLint y, GLint z ))
		NULL;
	fn.glVertex3s =
		( void (*)(GLshort x, GLshort y, GLshort z ))
		NULL;
	fn.glVertex4d =
		( void (*)(GLdouble x, GLdouble y, GLdouble z, GLdouble w ))
		NULL;
	fn.glVertex4f =
		( void (*)(GLfloat x, GLfloat y, GLfloat z, GLfloat w ))
		NULL;
	fn.glVertex4i =
		( void (*)(GLint x, GLint y, GLint z, GLint w ))
		NULL;
	fn.glVertex4s =
		( void (*)(GLshort x, GLshort y, GLshort z, GLshort w ))
		NULL;
	fn.glVertex2dv =
		( void (*)(const GLdouble *v ))
		NULL;
	fn.glVertex2fv =
		( void (*)(const GLfloat *v ))
		NULL;
	fn.glVertex2iv =
		( void (*)(const GLint *v ))
		NULL;
	fn.glVertex2sv =
		( void (*)(const GLshort *v ))
		NULL;
	fn.glVertex3dv =
		( void (*)(const GLdouble *v ))
		NULL;
	fn.glVertex3fv =
		( void (*)(const GLfloat *v ))
		NULL;
	fn.glVertex3iv =
		( void (*)(const GLint *v ))
		NULL;
	fn.glVertex3sv =
		( void (*)(const GLshort *v ))
		NULL;
	fn.glVertex4dv =
		( void (*)(const GLdouble *v ))
		NULL;
	fn.glVertex4fv =
		( void (*)(const GLfloat *v ))
		NULL;
	fn.glVertex4iv =
		( void (*)(const GLint *v ))
		NULL;
	fn.glVertex4sv =
		( void (*)(const GLshort *v ))
		NULL;
	fn.glNormal3b =
		( void (*)(GLbyte nx, GLbyte ny, GLbyte nz ))
		NULL;
	fn.glNormal3d =
		( void (*)(GLdouble nx, GLdouble ny, GLdouble nz ))
		NULL;
	fn.glNormal3f =
		( void (*)(GLfloat nx, GLfloat ny, GLfloat nz ))
		NULL;
	fn.glNormal3i =
		( void (*)(GLint nx, GLint ny, GLint nz ))
		NULL;
	fn.glNormal3s =
		( void (*)(GLshort nx, GLshort ny, GLshort nz ))
		NULL;
	fn.glNormal3bv =
		( void (*)(const GLbyte *v ))
		NULL;
	fn.glNormal3dv =
		( void (*)(const GLdouble *v ))
		NULL;
	fn.glNormal3fv =
		( void (*)(const GLfloat *v ))
		NULL;
	fn.glNormal3iv =
		( void (*)(const GLint *v ))
		NULL;
	fn.glNormal3sv =
		( void (*)(const GLshort *v ))
		NULL;
	fn.glIndexd =
		( void (*)(GLdouble c ))
		NULL;
	fn.glIndexf =
		( void (*)(GLfloat c ))
		NULL;
	fn.glIndexi =
		( void (*)(GLint c ))
		NULL;
	fn.glIndexs =
		( void (*)(GLshort c ))
		NULL;
	fn.glIndexub =
		( void (*)(GLubyte c ))
		NULL;
	fn.glIndexdv =
		( void (*)(const GLdouble *c ))
		NULL;
	fn.glIndexfv =
		( void (*)(const GLfloat *c ))
		NULL;
	fn.glIndexiv =
		( void (*)(const GLint *c ))
		NULL;
	fn.glIndexsv =
		( void (*)(const GLshort *c ))
		NULL;
	fn.glIndexubv =
		( void (*)(const GLubyte *c ))
		NULL;
	fn.glColor3b =
		( void (*)(GLbyte red, GLbyte green, GLbyte blue ))
		NULL;
	fn.glColor3d =
		( void (*)(GLdouble red, GLdouble green, GLdouble blue ))
		NULL;
	fn.glColor3f =
		( void (*)(GLfloat red, GLfloat green, GLfloat blue ))
		NULL;
	fn.glColor3i =
		( void (*)(GLint red, GLint green, GLint blue ))
		NULL;
	fn.glColor3s =
		( void (*)(GLshort red, GLshort green, GLshort blue ))
		NULL;
	fn.glColor3ub =
		( void (*)(GLubyte red, GLubyte green, GLubyte blue ))
		NULL;
	fn.glColor3ui =
		( void (*)(GLuint red, GLuint green, GLuint blue ))
		NULL;
	fn.glColor3us =
		( void (*)(GLushort red, GLushort green, GLushort blue ))
		NULL;
	fn.glColor4b =
		( void (*)(GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha ))
		NULL;
	fn.glColor4d =
		( void (*)(GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha ))
		NULL;
	fn.glColor4f =
		( void (*)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha ))
		NULL;
	fn.glColor4i =
		( void (*)(GLint red, GLint green, GLint blue, GLint alpha ))
		NULL;
	fn.glColor4s =
		( void (*)(GLshort red, GLshort green, GLshort blue, GLshort alpha ))
		NULL;
	fn.glColor4ub =
		( void (*)(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha ))
		NULL;
	fn.glColor4ui =
		( void (*)(GLuint red, GLuint green, GLuint blue, GLuint alpha ))
		NULL;
	fn.glColor4us =
		( void (*)(GLushort red, GLushort green, GLushort blue, GLushort alpha ))
		NULL;
	fn.glColor3bv =
		( void (*)(const GLbyte *v ))
		NULL;
	fn.glColor3dv =
		( void (*)(const GLdouble *v ))
		NULL;
	fn.glColor3fv =
		( void (*)(const GLfloat *v ))
		NULL;
	fn.glColor3iv =
		( void (*)(const GLint *v ))
		NULL;
	fn.glColor3sv =
		( void (*)(const GLshort *v ))
		NULL;
	fn.glColor3ubv =
		( void (*)(const GLubyte *v ))
		NULL;
	fn.glColor3uiv =
		( void (*)(const GLuint *v ))
		NULL;
	fn.glColor3usv =
		( void (*)(const GLushort *v ))
		NULL;
	fn.glColor4bv =
		( void (*)(const GLbyte *v ))
		NULL;
	fn.glColor4dv =
		( void (*)(const GLdouble *v ))
		NULL;
	fn.glColor4fv =
		( void (*)(const GLfloat *v ))
		NULL;
	fn.glColor4iv =
		( void (*)(const GLint *v ))
		NULL;
	fn.glColor4sv =
		( void (*)(const GLshort *v ))
		NULL;
	fn.glColor4ubv =
		( void (*)(const GLubyte *v ))
		NULL;
	fn.glColor4uiv =
		( void (*)(const GLuint *v ))
		NULL;
	fn.glColor4usv =
		( void (*)(const GLushort *v ))
		NULL;
	fn.glTexCoord1d =
		( void (*)(GLdouble s ))
		NULL;
	fn.glTexCoord1f =
		( void (*)(GLfloat s ))
		NULL;
	fn.glTexCoord1i =
		( void (*)(GLint s ))
		NULL;
	fn.glTexCoord1s =
		( void (*)(GLshort s ))
		NULL;
	fn.glTexCoord2d =
		( void (*)(GLdouble s, GLdouble t ))
		NULL;
	fn.glTexCoord2f =
		( void (*)(GLfloat s, GLfloat t ))
		NULL;
	fn.glTexCoord2i =
		( void (*)(GLint s, GLint t ))
		NULL;
	fn.glTexCoord2s =
		( void (*)(GLshort s, GLshort t ))
		NULL;
	fn.glTexCoord3d =
		( void (*)(GLdouble s, GLdouble t, GLdouble r ))
		NULL;
	fn.glTexCoord3f =
		( void (*)(GLfloat s, GLfloat t, GLfloat r ))
		NULL;
	fn.glTexCoord3i =
		( void (*)(GLint s, GLint t, GLint r ))
		NULL;
	fn.glTexCoord3s =
		( void (*)(GLshort s, GLshort t, GLshort r ))
		NULL;
	fn.glTexCoord4d =
		( void (*)(GLdouble s, GLdouble t, GLdouble r, GLdouble q ))
		NULL;
	fn.glTexCoord4f =
		( void (*)(GLfloat s, GLfloat t, GLfloat r, GLfloat q ))
		NULL;
	fn.glTexCoord4i =
		( void (*)(GLint s, GLint t, GLint r, GLint q ))
		NULL;
	fn.glTexCoord4s =
		( void (*)(GLshort s, GLshort t, GLshort r, GLshort q ))
		NULL;
	fn.glTexCoord1dv =
		( void (*)(const GLdouble *v ))
		NULL;
	fn.glTexCoord1fv =
		( void (*)(const GLfloat *v ))
		NULL;
	fn.glTexCoord1iv =
		( void (*)(const GLint *v ))
		NULL;
	fn.glTexCoord1sv =
		( void (*)(const GLshort *v ))
		NULL;
	fn.glTexCoord2dv =
		( void (*)(const GLdouble *v ))
		NULL;
	fn.glTexCoord2fv =
		( void (*)(const GLfloat *v ))
		NULL;
	fn.glTexCoord2iv =
		( void (*)(const GLint *v ))
		NULL;
	fn.glTexCoord2sv =
		( void (*)(const GLshort *v ))
		NULL;
	fn.glTexCoord3dv =
		( void (*)(const GLdouble *v ))
		NULL;
	fn.glTexCoord3fv =
		( void (*)(const GLfloat *v ))
		NULL;
	fn.glTexCoord3iv =
		( void (*)(const GLint *v ))
		NULL;
	fn.glTexCoord3sv =
		( void (*)(const GLshort *v ))
		NULL;
	fn.glTexCoord4dv =
		( void (*)(const GLdouble *v ))
		NULL;
	fn.glTexCoord4fv =
		( void (*)(const GLfloat *v ))
		NULL;
	fn.glTexCoord4iv =
		( void (*)(const GLint *v ))
		NULL;
	fn.glTexCoord4sv =
		( void (*)(const GLshort *v ))
		NULL;
	fn.glRasterPos2d =
		( void (*)(GLdouble x, GLdouble y ))
		NULL;
	fn.glRasterPos2f =
		( void (*)(GLfloat x, GLfloat y ))
		NULL;
	fn.glRasterPos2i =
		( void (*)(GLint x, GLint y ))
		NULL;
	fn.glRasterPos2s =
		( void (*)(GLshort x, GLshort y ))
		NULL;
	fn.glRasterPos3d =
		( void (*)(GLdouble x, GLdouble y, GLdouble z ))
		NULL;
	fn.glRasterPos3f =
		( void (*)(GLfloat x, GLfloat y, GLfloat z ))
		NULL;
	fn.glRasterPos3i =
		( void (*)(GLint x, GLint y, GLint z ))
		NULL;
	fn.glRasterPos3s =
		( void (*)(GLshort x, GLshort y, GLshort z ))
		NULL;
	fn.glRasterPos4d =
		( void (*)(GLdouble x, GLdouble y, GLdouble z, GLdouble w ))
		NULL;
	fn.glRasterPos4f =
		( void (*)(GLfloat x, GLfloat y, GLfloat z, GLfloat w ))
		NULL;
	fn.glRasterPos4i =
		( void (*)(GLint x, GLint y, GLint z, GLint w ))
		NULL;
	fn.glRasterPos4s =
		( void (*)(GLshort x, GLshort y, GLshort z, GLshort w ))
		NULL;
	fn.glRasterPos2dv =
		( void (*)(const GLdouble *v ))
		NULL;
	fn.glRasterPos2fv =
		( void (*)(const GLfloat *v ))
		NULL;
	fn.glRasterPos2iv =
		( void (*)(const GLint *v ))
		NULL;
	fn.glRasterPos2sv =
		( void (*)(const GLshort *v ))
		NULL;
	fn.glRasterPos3dv =
		( void (*)(const GLdouble *v ))
		NULL;
	fn.glRasterPos3fv =
		( void (*)(const GLfloat *v ))
		NULL;
	fn.glRasterPos3iv =
		( void (*)(const GLint *v ))
		NULL;
	fn.glRasterPos3sv =
		( void (*)(const GLshort *v ))
		NULL;
	fn.glRasterPos4dv =
		( void (*)(const GLdouble *v ))
		NULL;
	fn.glRasterPos4fv =
		( void (*)(const GLfloat *v ))
		NULL;
	fn.glRasterPos4iv =
		( void (*)(const GLint *v ))
		NULL;
	fn.glRasterPos4sv =
		( void (*)(const GLshort *v ))
		NULL;
	fn.glRectd =
		( void (*)(GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2 ))
		NULL;
	fn.glRectf =
		( void (*)(GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2 ))
		NULL;
	fn.glRecti =
		( void (*)(GLint x1, GLint y1, GLint x2, GLint y2 ))
		NULL;
	fn.glRects =
		( void (*)(GLshort x1, GLshort y1, GLshort x2, GLshort y2 ))
		NULL;
	fn.glRectdv =
		( void (*)(const GLdouble *v1, const GLdouble *v2 ))
		NULL;
	fn.glRectfv =
		( void (*)(const GLfloat *v1, const GLfloat *v2 ))
		NULL;
	fn.glRectiv =
		( void (*)(const GLint *v1, const GLint *v2 ))
		NULL;
	fn.glRectsv =
		( void (*)(const GLshort *v1, const GLshort *v2 ))
		NULL;
	fn.glVertexPointer =
		( void (*)(GLint size, GLenum type, GLsizei stride, const GLvoid *ptr ))
		NULL;
	fn.glNormalPointer =
		( void (*)(GLenum type, GLsizei stride, const GLvoid *ptr ))
		NULL;
	fn.glColorPointer =
		( void (*)(GLint size, GLenum type, GLsizei stride, const GLvoid *ptr ))
		NULL;
	fn.glIndexPointer =
		( void (*)(GLenum type, GLsizei stride, const GLvoid *ptr ))
		NULL;
	fn.glTexCoordPointer =
		( void (*)(GLint size, GLenum type, GLsizei stride, const GLvoid *ptr ))
		NULL;
	fn.glEdgeFlagPointer =
		( void (*)(GLsizei stride, const GLvoid *ptr ))
		NULL;
	fn.glGetPointerv =
		( void (*)(GLenum pname, GLvoid **params ))
		NULL;
	fn.glArrayElement =
		( void (*)(GLint i ))
		NULL;
	fn.glDrawArrays =
		( void (*)(GLenum mode, GLint first, GLsizei count ))
		NULL;
	fn.glDrawElements =
		( void (*)(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices ))
		NULL;
	fn.glInterleavedArrays =
		( void (*)(GLenum format, GLsizei stride, const GLvoid *pointer ))
		NULL;
	fn.glShadeModel =
		( void (*)(GLenum mode ))
		NULL;
	fn.glLightf =
		( void (*)(GLenum light, GLenum pname, GLfloat param ))
		NULL;
	fn.glLighti =
		( void (*)(GLenum light, GLenum pname, GLint param ))
		NULL;
	fn.glLightfv =
		( void (*)(GLenum light, GLenum pname, const GLfloat *params ))
		NULL;
	fn.glLightiv =
		( void (*)(GLenum light, GLenum pname, const GLint *params ))
		NULL;
	fn.glGetLightfv =
		( void (*)(GLenum light, GLenum pname, GLfloat *params ))
		NULL;
	fn.glGetLightiv =
		( void (*)(GLenum light, GLenum pname, GLint *params ))
		NULL;
	fn.glLightModelf =
		( void (*)(GLenum pname, GLfloat param ))
		NULL;
	fn.glLightModeli =
		( void (*)(GLenum pname, GLint param ))
		NULL;
	fn.glLightModelfv =
		( void (*)(GLenum pname, const GLfloat *params ))
		NULL;
	fn.glLightModeliv =
		( void (*)(GLenum pname, const GLint *params ))
		NULL;
	fn.glMaterialf =
		( void (*)(GLenum face, GLenum pname, GLfloat param ))
		NULL;
	fn.glMateriali =
		( void (*)(GLenum face, GLenum pname, GLint param ))
		NULL;
	fn.glMaterialfv =
		( void (*)(GLenum face, GLenum pname, const GLfloat *params ))
		NULL;
	fn.glMaterialiv =
		( void (*)(GLenum face, GLenum pname, const GLint *params ))
		NULL;
	fn.glGetMaterialfv =
		( void (*)(GLenum face, GLenum pname, GLfloat *params ))
		NULL;
	fn.glGetMaterialiv =
		( void (*)(GLenum face, GLenum pname, GLint *params ))
		NULL;
	fn.glColorMaterial =
		( void (*)(GLenum face, GLenum mode ))
		NULL;
	fn.glPixelZoom =
		( void (*)(GLfloat xfactor, GLfloat yfactor ))
		NULL;
	fn.glPixelStoref =
		( void (*)(GLenum pname, GLfloat param ))
		NULL;
	fn.glPixelStorei =
		( void (*)(GLenum pname, GLint param ))
		NULL;
	fn.glPixelTransferf =
		( void (*)(GLenum pname, GLfloat param ))
		NULL;
	fn.glPixelTransferi =
		( void (*)(GLenum pname, GLint param ))
		NULL;
	fn.glPixelMapfv =
		( void (*)(GLenum map, GLsizei mapsize, const GLfloat *values ))
		NULL;
	fn.glPixelMapuiv =
		( void (*)(GLenum map, GLsizei mapsize, const GLuint *values ))
		NULL;
	fn.glPixelMapusv =
		( void (*)(GLenum map, GLsizei mapsize, const GLushort *values ))
		NULL;
	fn.glGetPixelMapfv =
		( void (*)(GLenum map, GLfloat *values ))
		NULL;
	fn.glGetPixelMapuiv =
		( void (*)(GLenum map, GLuint *values ))
		NULL;
	fn.glGetPixelMapusv =
		( void (*)(GLenum map, GLushort *values ))
		NULL;
	fn.glBitmap =
		( void (*)(GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap ))
		NULL;
	fn.glReadPixels =
		( void (*)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels ))
		NULL;
	fn.glDrawPixels =
		( void (*)(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels ))
		NULL;
	fn.glCopyPixels =
		( void (*)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type ))
		NULL;
	fn.glStencilFunc =
		( void (*)(GLenum func, GLint ref, GLuint mask ))
		NULL;
	fn.glStencilMask =
		( void (*)(GLuint mask ))
		NULL;
	fn.glStencilOp =
		( void (*)(GLenum fail, GLenum zfail, GLenum zpass ))
		NULL;
	fn.glClearStencil =
		( void (*)(GLint s ))
		NULL;
	fn.glTexGend =
		( void (*)(GLenum coord, GLenum pname, GLdouble param ))
		NULL;
	fn.glTexGenf =
		( void (*)(GLenum coord, GLenum pname, GLfloat param ))
		NULL;
	fn.glTexGeni =
		( void (*)(GLenum coord, GLenum pname, GLint param ))
		NULL;
	fn.glTexGendv =
		( void (*)(GLenum coord, GLenum pname, const GLdouble *params ))
		NULL;
	fn.glTexGenfv =
		( void (*)(GLenum coord, GLenum pname, const GLfloat *params ))
		NULL;
	fn.glTexGeniv =
		( void (*)(GLenum coord, GLenum pname, const GLint *params ))
		NULL;
	fn.glGetTexGendv =
		( void (*)(GLenum coord, GLenum pname, GLdouble *params ))
		NULL;
	fn.glGetTexGenfv =
		( void (*)(GLenum coord, GLenum pname, GLfloat *params ))
		NULL;
	fn.glGetTexGeniv =
		( void (*)(GLenum coord, GLenum pname, GLint *params ))
		NULL;
	fn.glTexEnvf =
		( void (*)(GLenum target, GLenum pname, GLfloat param ))
		NULL;
	fn.glTexEnvi =
		( void (*)(GLenum target, GLenum pname, GLint param ))
		NULL;
	fn.glTexEnvfv =
		( void (*)(GLenum target, GLenum pname, const GLfloat *params ))
		NULL;
	fn.glTexEnviv =
		( void (*)(GLenum target, GLenum pname, const GLint *params ))
		NULL;
	fn.glGetTexEnvfv =
		( void (*)(GLenum target, GLenum pname, GLfloat *params ))
		NULL;
	fn.glGetTexEnviv =
		( void (*)(GLenum target, GLenum pname, GLint *params ))
		NULL;
	fn.glTexParameterf =
		( void (*)(GLenum target, GLenum pname, GLfloat param ))
		NULL;
	fn.glTexParameteri =
		( void (*)(GLenum target, GLenum pname, GLint param ))
		NULL;
	fn.glTexParameterfv =
		( void (*)(GLenum target, GLenum pname, const GLfloat *params ))
		NULL;
	fn.glTexParameteriv =
		( void (*)(GLenum target, GLenum pname, const GLint *params ))
		NULL;
	fn.glGetTexParameterfv =
		( void (*)(GLenum target, GLenum pname, GLfloat *params))
		NULL;
	fn.glGetTexParameteriv =
		( void (*)(GLenum target, GLenum pname, GLint *params ))
		NULL;
	fn.glGetTexLevelParameterfv =
		( void (*)(GLenum target, GLint level, GLenum pname, GLfloat *params ))
		NULL;
	fn.glGetTexLevelParameteriv =
		( void (*)(GLenum target, GLint level, GLenum pname, GLint *params ))
		NULL;
	fn.glTexImage1D =
		( void (*)(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels ))
		NULL;
	fn.glTexImage2D =
		( void (*)(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels ))
		NULL;
	fn.glGetTexImage =
		( void (*)(GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels ))
		NULL;
	fn.glGenTextures =
		( void (*)(GLsizei n, GLuint *textures ))
		NULL;
	fn.glDeleteTextures =
		( void (*)(GLsizei n, const GLuint *textures))
		NULL;
	fn.glBindTexture =
		( void (*)(GLenum target, GLuint texture ))
		NULL;
	fn.glPrioritizeTextures =
		( void (*)(GLsizei n, const GLuint *textures, const GLclampf *priorities ))
		NULL;
	fn.glAreTexturesResident =
		( GLboolean (*)(GLsizei n, const GLuint *textures, GLboolean *residences ))
		NULL;
	fn.glIsTexture =
		( GLboolean (*)(GLuint texture ))
		NULL;
	fn.glTexSubImage1D =
		( void (*)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels ))
		NULL;
	fn.glTexSubImage2D =
		( void (*)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels ))
		NULL;
	fn.glCopyTexImage1D =
		( void (*)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border ))
		NULL;
	fn.glCopyTexImage2D =
		( void (*)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border ))
		NULL;
	fn.glCopyTexSubImage1D =
		( void (*)(GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width ))
		NULL;
	fn.glCopyTexSubImage2D =
		( void (*)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height ))
		NULL;
	fn.glMap1d =
		( void (*)(GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points ))
		NULL;
	fn.glMap1f =
		( void (*)(GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points ))
		NULL;
	fn.glMap2d =
		( void (*)(GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points ))
		NULL;
	fn.glMap2f =
		( void (*)(GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points ))
		NULL;
	fn.glGetMapdv =
		( void (*)(GLenum target, GLenum query, GLdouble *v ))
		NULL;
	fn.glGetMapfv =
		( void (*)(GLenum target, GLenum query, GLfloat *v ))
		NULL;
	fn.glGetMapiv =
		( void (*)(GLenum target, GLenum query, GLint *v ))
		NULL;
	fn.glEvalCoord1d =
		( void (*)(GLdouble u ))
		NULL;
	fn.glEvalCoord1f =
		( void (*)(GLfloat u ))
		NULL;
	fn.glEvalCoord1dv =
		( void (*)(const GLdouble *u ))
		NULL;
	fn.glEvalCoord1fv =
		( void (*)(const GLfloat *u ))
		NULL;
	fn.glEvalCoord2d =
		( void (*)(GLdouble u, GLdouble v ))
		NULL;
	fn.glEvalCoord2f =
		( void (*)(GLfloat u, GLfloat v ))
		NULL;
	fn.glEvalCoord2dv =
		( void (*)(const GLdouble *u ))
		NULL;
	fn.glEvalCoord2fv =
		( void (*)(const GLfloat *u ))
		NULL;
	fn.glMapGrid1d =
		( void (*)(GLint un, GLdouble u1, GLdouble u2 ))
		NULL;
	fn.glMapGrid1f =
		( void (*)(GLint un, GLfloat u1, GLfloat u2 ))
		NULL;
	fn.glMapGrid2d =
		( void (*)(GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2 ))
		NULL;
	fn.glMapGrid2f =
		( void (*)(GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2 ))
		NULL;
	fn.glEvalPoint1 =
		( void (*)(GLint i ))
		NULL;
	fn.glEvalPoint2 =
		( void (*)(GLint i, GLint j ))
		NULL;
	fn.glEvalMesh1 =
		( void (*)(GLenum mode, GLint i1, GLint i2 ))
		NULL;
	fn.glEvalMesh2 =
		( void (*)(GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2 ))
		NULL;
	fn.glFogf =
		( void (*)(GLenum pname, GLfloat param ))
		NULL;
	fn.glFogi =
		( void (*)(GLenum pname, GLint param ))
		NULL;
	fn.glFogfv =
		( void (*)(GLenum pname, const GLfloat *params ))
		NULL;
	fn.glFogiv =
		( void (*)(GLenum pname, const GLint *params ))
		NULL;
	fn.glFeedbackBuffer =
		( void (*)(GLsizei size, GLenum type, GLfloat *buffer ))
		NULL;
	fn.glPassThrough =
		( void (*)(GLfloat token ))
		NULL;
	fn.glSelectBuffer =
		( void (*)(GLsizei size, GLuint *buffer ))
		NULL;
	fn.glInitNames =
		( void (*)(void))
		NULL;
	fn.glLoadName =
		( void (*)(GLuint name ))
		NULL;
	fn.glPushName =
		( void (*)(GLuint name ))
		NULL;
	fn.glPopName =
		( void (*)(void))
		NULL;
	fn.glEnableTraceMESA =
		( void (*)(GLbitfield mask ))
		NULL;
	fn.glDisableTraceMESA =
		( void (*)(GLbitfield mask ))
		NULL;
	fn.glNewTraceMESA =
		( void (*)(GLbitfield mask, const GLubyte * traceName ))
		NULL;
	fn.glEndTraceMESA =
		( void (*)(void))
		NULL;
	fn.glTraceAssertAttribMESA =
		( void (*)(GLbitfield attribMask ))
		NULL;
	fn.glTraceCommentMESA =
		( void (*)(const GLubyte * comment ))
		NULL;
	fn.glTraceTextureMESA =
		( void (*)(GLuint name, const GLubyte* comment ))
		NULL;
	fn.glTraceListMESA =
		( void (*)(GLuint name, const GLubyte* comment ))
		NULL;
	fn.glTracePointerMESA =
		( void (*)(GLvoid* pointer, const GLubyte* comment ))
		NULL;
	fn.glTracePointerRangeMESA =
		( void (*)(const GLvoid* first, const GLvoid* last, const GLubyte* comment ))
		NULL;
	fn.glBlendEquationSeparateATI =
		( void (*)(GLenum modeRGB, GLenum modeA ))
		NULL;
/* Functions generated : 347 */
