#
# Makefile for $(CPU) object modules
#

SHELL = /bin/sh
SUBDIRS = 

srcdir = .
top_srcdir = ../../../..
subdir = .xfso

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here: objs

INCLUDES = -I.. -I../.natfeat -I$(top_srcdir)
CFLAGS += $(MDFLAGS)

# default definitions
OBJS = $(COBJS:.c=.o)

objs: $(OBJS)


# default dependencies
# must be included last
include $(top_srcdir)/DEPENDENCIES
